'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from anchorpy.error import ProgramError

class NotImplemented(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            0, ""
        )

    code = 0
    name = "NotImplemented"
    msg = ""
class MissingRequiredSignature(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            1, ""
        )

    code = 1
    name = "MissingRequiredSignature"
    msg = ""
class InvalidChannelStatus(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2, ""
        )

    code = 2
    name = "InvalidChannelStatus"
    msg = ""
class InvalidAccountDiscriminator(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            3, ""
        )

    code = 3
    name = "InvalidAccountDiscriminator"
    msg = ""
class UnsupportedChannelVersion(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            4, ""
        )

    code = 4
    name = "UnsupportedChannelVersion"
    msg = ""
class InvalidChannelPayer(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            5, ""
        )

    code = 5
    name = "InvalidChannelPayer"
    msg = ""
class InvalidChannelPayee(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            6, ""
        )

    code = 6
    name = "InvalidChannelPayee"
    msg = ""
class InvalidChannelMint(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            7, ""
        )

    code = 7
    name = "InvalidChannelMint"
    msg = ""
class InvalidEventAuthority(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            8, ""
        )

    code = 8
    name = "InvalidEventAuthority"
    msg = ""
class NotEnoughAccountKeys(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            9, ""
        )

    code = 9
    name = "NotEnoughAccountKeys"
    msg = ""
class ChannelAccountMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            50, ""
        )

    code = 50
    name = "ChannelAccountMismatch"
    msg = ""
class InvalidChannelTokenAccount(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            51, ""
        )

    code = 51
    name = "InvalidChannelTokenAccount"
    msg = ""
class InvalidChannelTokenExtensions(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            52, ""
        )

    code = 52
    name = "InvalidChannelTokenExtensions"
    msg = ""
class MintAccountMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            53, ""
        )

    code = 53
    name = "MintAccountMismatch"
    msg = ""
class InvalidMintTokenProgram(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            54, ""
        )

    code = 54
    name = "InvalidMintTokenProgram"
    msg = ""
class MalformedMintTokenAccountData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            55, ""
        )

    code = 55
    name = "MalformedMintTokenAccountData"
    msg = ""
class MalformedMintTokenExtensions(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            56, ""
        )

    code = 56
    name = "MalformedMintTokenExtensions"
    msg = ""
class PayerAccountMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            57, ""
        )

    code = 57
    name = "PayerAccountMismatch"
    msg = ""
class InvalidPayerTokenAccount(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            58, ""
        )

    code = 58
    name = "InvalidPayerTokenAccount"
    msg = ""
class InvalidPayerTokenExtensions(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            59, ""
        )

    code = 59
    name = "InvalidPayerTokenExtensions"
    msg = ""
class PayeeAccountMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            60, ""
        )

    code = 60
    name = "PayeeAccountMismatch"
    msg = ""
class InvalidPayeeTokenAccount(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            61, ""
        )

    code = 61
    name = "InvalidPayeeTokenAccount"
    msg = ""
class InvalidPayeeTokenExtensions(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            62, ""
        )

    code = 62
    name = "InvalidPayeeTokenExtensions"
    msg = ""
class DepositMustBeNonZero(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            200, ""
        )

    code = 200
    name = "DepositMustBeNonZero"
    msg = ""
class GracePeriodMustBeNonZero(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            201, ""
        )

    code = 201
    name = "GracePeriodMustBeNonZero"
    msg = ""
class MissingEd25519Verification(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            230, ""
        )

    code = 230
    name = "MissingEd25519Verification"
    msg = ""
class MalformedEd25519Instruction(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            231, ""
        )

    code = 231
    name = "MalformedEd25519Instruction"
    msg = ""
class VoucherChannelMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            232, ""
        )

    code = 232
    name = "VoucherChannelMismatch"
    msg = ""
class VoucherExpired(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            233, ""
        )

    code = 233
    name = "VoucherExpired"
    msg = ""
class VoucherWatermarkNotMonotonic(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            234, ""
        )

    code = 234
    name = "VoucherWatermarkNotMonotonic"
    msg = ""
class VoucherOverDeposit(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            235, ""
        )

    code = 235
    name = "VoucherOverDeposit"
    msg = ""
class VoucherMessageMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            236, ""
        )

    code = 236
    name = "VoucherMessageMismatch"
    msg = ""
class VoucherSignerMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            237, ""
        )

    code = 237
    name = "VoucherSignerMismatch"
    msg = ""
class InvalidRecipientCount(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            260, ""
        )

    code = 260
    name = "InvalidRecipientCount"
    msg = ""
class InvalidSplitConfig(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            261, ""
        )

    code = 261
    name = "InvalidSplitConfig"
    msg = ""
class DistributionPartsOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            262, ""
        )

    code = 262
    name = "DistributionPartsOverflow"
    msg = ""
class DuplicateRecipient(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            263, ""
        )

    code = 263
    name = "DuplicateRecipient"
    msg = ""
class DistributionAmountOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            264, ""
        )

    code = 264
    name = "DistributionAmountOverflow"
    msg = ""
class DistributionPreimageLengthOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            265, ""
        )

    code = 265
    name = "DistributionPreimageLengthOverflow"
    msg = ""
class ChannelAddressMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2000, ""
        )

    code = 2000
    name = "ChannelAddressMismatch"
    msg = ""
class PayerPayeeMustDiffer(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2001, ""
        )

    code = 2001
    name = "PayerPayeeMustDiffer"
    msg = ""
class InvalidAuthorizedSigner(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2002, ""
        )

    code = 2002
    name = "InvalidAuthorizedSigner"
    msg = ""
class TopUpDepositOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2100, ""
        )

    code = 2100
    name = "TopUpDepositOverflow"
    msg = ""
class FinalizeDeadlineOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2200, ""
        )

    code = 2200
    name = "FinalizeDeadlineOverflow"
    msg = ""
class PayerAlreadyWithdrawn(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2300, ""
        )

    code = 2300
    name = "PayerAlreadyWithdrawn"
    msg = ""
class RefundCalculationOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2301, ""
        )

    code = 2301
    name = "RefundCalculationOverflow"
    msg = ""
class ChannelNotDistributable(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2400, ""
        )

    code = 2400
    name = "ChannelNotDistributable"
    msg = ""
class TreasuryAccountMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2401, ""
        )

    code = 2401
    name = "TreasuryAccountMismatch"
    msg = ""
class InvalidTreasuryTokenAccount(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2402, ""
        )

    code = 2402
    name = "InvalidTreasuryTokenAccount"
    msg = ""
class InvalidTreasuryTokenExtensions(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2403, ""
        )

    code = 2403
    name = "InvalidTreasuryTokenExtensions"
    msg = ""
class RecipientAccountMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2404, ""
        )

    code = 2404
    name = "RecipientAccountMismatch"
    msg = ""
class InvalidRecipientTokenAccount(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2405, ""
        )

    code = 2405
    name = "InvalidRecipientTokenAccount"
    msg = ""
class InvalidRecipientTokenExtensions(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2406, ""
        )

    code = 2406
    name = "InvalidRecipientTokenExtensions"
    msg = ""
class InvalidDistributionHash(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2407, ""
        )

    code = 2407
    name = "InvalidDistributionHash"
    msg = ""
class NothingToDistribute(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2408, ""
        )

    code = 2408
    name = "NothingToDistribute"
    msg = ""
class RecipientAccountCountMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2409, ""
        )

    code = 2409
    name = "RecipientAccountCountMismatch"
    msg = ""
class DistributePoolOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2410, ""
        )

    code = 2410
    name = "DistributePoolOverflow"
    msg = ""
class DistributeBalanceCalculationOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2411, ""
        )

    code = 2411
    name = "DistributeBalanceCalculationOverflow"
    msg = ""
class DistributePayerBalanceOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2412, ""
        )

    code = 2412
    name = "DistributePayerBalanceOverflow"
    msg = ""
class DistributeTransferQueueOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            2413, ""
        )

    code = 2413
    name = "DistributeTransferQueueOverflow"
    msg = ""

CustomError = typing.Union[
    NotImplemented,
    MissingRequiredSignature,
    InvalidChannelStatus,
    InvalidAccountDiscriminator,
    UnsupportedChannelVersion,
    InvalidChannelPayer,
    InvalidChannelPayee,
    InvalidChannelMint,
    InvalidEventAuthority,
    NotEnoughAccountKeys,
    ChannelAccountMismatch,
    InvalidChannelTokenAccount,
    InvalidChannelTokenExtensions,
    MintAccountMismatch,
    InvalidMintTokenProgram,
    MalformedMintTokenAccountData,
    MalformedMintTokenExtensions,
    PayerAccountMismatch,
    InvalidPayerTokenAccount,
    InvalidPayerTokenExtensions,
    PayeeAccountMismatch,
    InvalidPayeeTokenAccount,
    InvalidPayeeTokenExtensions,
    DepositMustBeNonZero,
    GracePeriodMustBeNonZero,
    MissingEd25519Verification,
    MalformedEd25519Instruction,
    VoucherChannelMismatch,
    VoucherExpired,
    VoucherWatermarkNotMonotonic,
    VoucherOverDeposit,
    VoucherMessageMismatch,
    VoucherSignerMismatch,
    InvalidRecipientCount,
    InvalidSplitConfig,
    DistributionPartsOverflow,
    DuplicateRecipient,
    DistributionAmountOverflow,
    DistributionPreimageLengthOverflow,
    ChannelAddressMismatch,
    PayerPayeeMustDiffer,
    InvalidAuthorizedSigner,
    TopUpDepositOverflow,
    FinalizeDeadlineOverflow,
    PayerAlreadyWithdrawn,
    RefundCalculationOverflow,
    ChannelNotDistributable,
    TreasuryAccountMismatch,
    InvalidTreasuryTokenAccount,
    InvalidTreasuryTokenExtensions,
    RecipientAccountMismatch,
    InvalidRecipientTokenAccount,
    InvalidRecipientTokenExtensions,
    InvalidDistributionHash,
    NothingToDistribute,
    RecipientAccountCountMismatch,
    DistributePoolOverflow,
    DistributeBalanceCalculationOverflow,
    DistributePayerBalanceOverflow,
    DistributeTransferQueueOverflow,
 ]
CUSTOM_ERROR_MAP: dict[int, CustomError] = {
    0: NotImplemented(),
    1: MissingRequiredSignature(),
    2: InvalidChannelStatus(),
    3: InvalidAccountDiscriminator(),
    4: UnsupportedChannelVersion(),
    5: InvalidChannelPayer(),
    6: InvalidChannelPayee(),
    7: InvalidChannelMint(),
    8: InvalidEventAuthority(),
    9: NotEnoughAccountKeys(),
    50: ChannelAccountMismatch(),
    51: InvalidChannelTokenAccount(),
    52: InvalidChannelTokenExtensions(),
    53: MintAccountMismatch(),
    54: InvalidMintTokenProgram(),
    55: MalformedMintTokenAccountData(),
    56: MalformedMintTokenExtensions(),
    57: PayerAccountMismatch(),
    58: InvalidPayerTokenAccount(),
    59: InvalidPayerTokenExtensions(),
    60: PayeeAccountMismatch(),
    61: InvalidPayeeTokenAccount(),
    62: InvalidPayeeTokenExtensions(),
    200: DepositMustBeNonZero(),
    201: GracePeriodMustBeNonZero(),
    230: MissingEd25519Verification(),
    231: MalformedEd25519Instruction(),
    232: VoucherChannelMismatch(),
    233: VoucherExpired(),
    234: VoucherWatermarkNotMonotonic(),
    235: VoucherOverDeposit(),
    236: VoucherMessageMismatch(),
    237: VoucherSignerMismatch(),
    260: InvalidRecipientCount(),
    261: InvalidSplitConfig(),
    262: DistributionPartsOverflow(),
    263: DuplicateRecipient(),
    264: DistributionAmountOverflow(),
    265: DistributionPreimageLengthOverflow(),
    2000: ChannelAddressMismatch(),
    2001: PayerPayeeMustDiffer(),
    2002: InvalidAuthorizedSigner(),
    2100: TopUpDepositOverflow(),
    2200: FinalizeDeadlineOverflow(),
    2300: PayerAlreadyWithdrawn(),
    2301: RefundCalculationOverflow(),
    2400: ChannelNotDistributable(),
    2401: TreasuryAccountMismatch(),
    2402: InvalidTreasuryTokenAccount(),
    2403: InvalidTreasuryTokenExtensions(),
    2404: RecipientAccountMismatch(),
    2405: InvalidRecipientTokenAccount(),
    2406: InvalidRecipientTokenExtensions(),
    2407: InvalidDistributionHash(),
    2408: NothingToDistribute(),
    2409: RecipientAccountCountMismatch(),
    2410: DistributePoolOverflow(),
    2411: DistributeBalanceCalculationOverflow(),
    2412: DistributePayerBalanceOverflow(),
    2413: DistributeTransferQueueOverflow(),
}

def from_code(code: int) -> typing.Optional[CustomError]:
    maybe_err = CUSTOM_ERROR_MAP.get(code)
    if maybe_err is None:
        return None
    return maybe_err

