#!/usr/bin/env bash
#
# CI gate: fail if `go fix` (the Go 1.26 language/stdlib modernizers) would
# still change any NON-generated Go source in the module tree. This keeps the
# SDK on the newer idioms (any, min/max, new(expr), range-over-int, slices/maps
# helpers, strings.SplitSeq, wg.Go, ...) without leaving "use the newer API"
# review comments.
#
# The `inline` analyzer is deliberately DISABLED (-inline=false). It applies
# project-authored `//go:fix inline` directives, which are an opt-in migration
# aid rather than a language-modernization invariant: inlining a caller orphans
# the annotated helper, and the analyzer's results are cache/environment
# sensitive, which would make this gate fail in ways contributors cannot
# reproduce. The remaining modernizers are purely syntactic and deterministic.
# Run `go fix -inline ./...` by hand when you want to apply the inline directives.
#
# Generated files ("Code generated ... DO NOT EDIT" and the codama clients'
# "AUTOGENERATED using the codama library" header) are excluded: they are never
# hand-edited and are refreshed by the regen-diff gate instead. To satisfy this
# gate, run `go fix -inline=false ./...` in the affected module and commit.
#
# Runs from anywhere. Requires Go 1.26+ (the module's go directive selects it).
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fail=0

for mod in go harness/go-server harness/go-client; do
  [ -f "$ROOT/$mod/go.mod" ] || continue
  diff="$(cd "$ROOT/$mod" && go fix -inline=false -diff ./... 2>/dev/null)"
  [ -n "$diff" ] || continue
  mod_fail=0
  # The unified diff names each changed file on a '--- <abs-path> (old)' line.
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    # Exclude generated sources. Matches both the standard Go convention
    # ("Code generated ... DO NOT EDIT") and the codama header
    # ("This code was AUTOGENERATED using the codama library").
    if head -5 "$f" 2>/dev/null | grep -qiE 'code generated|autogenerated|@generated'; then
      continue
    fi
    echo "  needs 'go fix': ${f#"$ROOT"/}"
    fail=1
    mod_fail=1
  done < <(printf '%s\n' "$diff" | sed -n 's/^--- \(.*\) (old)$/\1/p')
  # On failure, show the exact modernizations so the fix is copy-pasteable and
  # never a mystery to a contributor who cannot reproduce the runner's tree.
  if [ "$mod_fail" -ne 0 ]; then
    echo "--- suggested modernizations (module: $mod) ---"
    printf '%s\n' "$diff" | sed "s#$ROOT/##g"
    echo "--- end ---"
  fi
done

if [ "$fail" -ne 0 ]; then
  echo "go-fix gate FAILED: run 'go fix -inline=false ./...' in the module(s) above and commit (generated files are excluded)."
  exit 1
fi
echo "go-fix gate OK: all non-generated Go is modernized."
