/**
 * CI vitest config: runs ALL tests (unit + surfpool integration) with coverage.
 * Used in CI after surfpool-sdk-node has been built and linked.
 */
import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        include: ['packages/*/src/__tests__/*.test.ts'],
        // Exclude surfpool-service-based tests and the playground e2e suites
        // (those need the playground server's dependencies and a sandbox).
        exclude: ['**/integration.test.ts', '**/*-e2e.test.ts'],
        testTimeout: 30_000,
        globals: true,
        coverage: {
            provider: 'v8',
            reporter: ['text', 'lcov', 'json-summary'],
            reportsDirectory: 'coverage',
            include: ['packages/*/src/**/*.ts'],
            // Exclude tests, build output, the Codama-autogenerated program client
            // ("DO NOT EDIT" — same rationale as the Rust src/generated exclusion),
            // and barrel re-export files (index.ts) that contain no logic.
            exclude: [
                '**/__tests__/**',
                '**/dist/**',
                '**/*.test.ts',
                '**/generated/**',
                '**/*.gen.ts',
                '**/index.ts',
            ],
            // Enforce a >=90% floor on all four metrics so the TS reference SDK is
            // gated like the other languages (previously coverage was collected
            // but never enforced). Current: lines ~98, branches ~92, functions
            // ~98, statements ~96.
            thresholds: {
                lines: 90,
                branches: 90,
                functions: 90,
                statements: 90,
            },
        },
    },
});
