'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class DistributionEntryJSON(typing.TypedDict):
    recipient: str
    bps: int

@dataclass
class DistributionEntry:
    layout: typing.ClassVar = borsh.CStruct(
        "recipient" /BorshPubkey,
        "bps" /borsh.U16,
        )
    #fields
    recipient: SolPubkey
    bps: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "DistributionEntry":
        return cls(
        recipient=obj["recipient"],
        bps=obj["bps"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "recipient": self.recipient,
                "bps": self.bps,
                }

    def to_json(self) -> DistributionEntryJSON:
        return {
                "recipient": str(self.recipient),
                "bps": self.bps,
                }

    @classmethod
    def from_json(cls, obj: DistributionEntryJSON) -> "DistributionEntry":
        return cls(
                recipient=SolPubkey.from_string(obj["recipient"]),
                bps=obj["bps"],
        )






