'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class OpenedJSON(typing.TypedDict):
    channel: str

@dataclass
class Opened:
    layout: typing.ClassVar = borsh.CStruct(
        "channel" /BorshPubkey,
        )
    #fields
    channel: SolPubkey
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "Opened":
        return cls(
        channel=obj["channel"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "channel": self.channel,
                }

    def to_json(self) -> OpenedJSON:
        return {
                "channel": str(self.channel),
                }

    @classmethod
    def from_json(cls, obj: OpenedJSON) -> "Opened":
        return cls(
                channel=SolPubkey.from_string(obj["channel"]),
        )






