'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class SettleAndFinalizeArgsJSON(typing.TypedDict):
    hasVoucher: int

@dataclass
class SettleAndFinalizeArgs:
    layout: typing.ClassVar = borsh.CStruct(
        "hasVoucher" /borsh.U8,
        )
    #fields
    hasVoucher: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "SettleAndFinalizeArgs":
        return cls(
        hasVoucher=obj["hasVoucher"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "hasVoucher": self.hasVoucher,
                }

    def to_json(self) -> SettleAndFinalizeArgsJSON:
        return {
                "hasVoucher": self.hasVoucher,
                }

    @classmethod
    def from_json(cls, obj: SettleAndFinalizeArgsJSON) -> "SettleAndFinalizeArgs":
        return cls(
                hasVoucher=obj["hasVoucher"],
        )






