'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass
from . import voucherArgs

class SettleArgsJSON(typing.TypedDict):
    voucher: voucherArgs.VoucherArgsJSON

@dataclass
class SettleArgs:
    layout: typing.ClassVar = borsh.CStruct(
        "voucher" /voucherArgs.VoucherArgs.layout,
        )
    #fields
    voucher: voucherArgs.VoucherArgs
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "SettleArgs":
        return cls(
        voucher=voucherArgs.VoucherArgs.from_decoded(obj["voucher"]),
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "voucher": self.voucher.to_encodable(),
                }

    def to_json(self) -> SettleArgsJSON:
        return {
                "voucher": self.voucher.to_json(),
                }

    @classmethod
    def from_json(cls, obj: SettleArgsJSON) -> "SettleArgs":
        return cls(
                voucher=voucherArgs.VoucherArgs.from_json(obj["voucher"]),
        )






