'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class TopUpArgsJSON(typing.TypedDict):
    amount: int

@dataclass
class TopUpArgs:
    layout: typing.ClassVar = borsh.CStruct(
        "amount" /borsh.U64,
        )
    #fields
    amount: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "TopUpArgs":
        return cls(
        amount=obj["amount"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "amount": self.amount,
                }

    def to_json(self) -> TopUpArgsJSON:
        return {
                "amount": self.amount,
                }

    @classmethod
    def from_json(cls, obj: TopUpArgsJSON) -> "TopUpArgs":
        return cls(
                amount=obj["amount"],
        )






