'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

from . import channel
from .channel import Channel, ChannelJSON
from . import closedChannel
from .closedChannel import ClosedChannel, ClosedChannelJSON
