'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import PAYMENT_CHANNELS_PROGRAM_ADDRESS


class ChannelJSON(typing.TypedDict):
    version: int
    bump: int
    status: int
    salt: int
    deposit: int
    settlement: types.settlementWatermarks.SettlementWatermarksJSON
    closureStartedAt: int
    payerWithdrawnAt: int
    gracePeriod: int
    distributionHash: list[int]
    payer: str
    payee: str
    authorizedSigner: str
    mint: str
    rentPayer: str
    openSlot: int

@dataclass
class Channel:
    #fields
    version: int
    bump: int
    status: int
    salt: int
    deposit: int
    settlement: types.settlementWatermarks.SettlementWatermarks
    closureStartedAt: int
    payerWithdrawnAt: int
    gracePeriod: int
    distributionHash: list[int]
    payer: SolPubkey
    payee: SolPubkey
    authorizedSigner: SolPubkey
    mint: SolPubkey
    rentPayer: SolPubkey
    openSlot: int



    layout: typing.ClassVar = borsh.CStruct(
        "version" /borsh.U8,
        "bump" /borsh.U8,
        "status" /borsh.U8,
        "salt" /borsh.U64,
        "deposit" /borsh.U64,
        "settlement" /types.settlementWatermarks.SettlementWatermarks.layout,
        "closureStartedAt" /borsh.I64,
        "payerWithdrawnAt" /borsh.I64,
        "gracePeriod" /borsh.U32,
        "distributionHash" /borsh.U8[32],
        "payer" /BorshPubkey,
        "payee" /BorshPubkey,
        "authorizedSigner" /BorshPubkey,
        "mint" /BorshPubkey,
        "rentPayer" /BorshPubkey,
        "openSlot" /borsh.U64,
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    ) -> typing.Optional["Channel"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    ) -> typing.List[typing.Optional["Channel"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["Channel"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "Channel":
        dec = Channel.layout.parse(data[1:])
        return cls(
                version=dec.version,
                bump=dec.bump,
                status=dec.status,
                salt=dec.salt,
                deposit=dec.deposit,
                settlement=types.settlementWatermarks.SettlementWatermarks.from_decoded(dec.settlement),
                closureStartedAt=dec.closureStartedAt,
                payerWithdrawnAt=dec.payerWithdrawnAt,
                gracePeriod=dec.gracePeriod,
                distributionHash=dec.distributionHash,
                payer=dec.payer,
                payee=dec.payee,
                authorizedSigner=dec.authorizedSigner,
                mint=dec.mint,
                rentPayer=dec.rentPayer,
                openSlot=dec.openSlot,
                )
    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "version": self.version,
                "bump": self.bump,
                "status": self.status,
                "salt": self.salt,
                "deposit": self.deposit,
                "settlement": self.settlement.to_encodable(),
                "closureStartedAt": self.closureStartedAt,
                "payerWithdrawnAt": self.payerWithdrawnAt,
                "gracePeriod": self.gracePeriod,
                "distributionHash": self.distributionHash,
                "payer": self.payer,
                "payee": self.payee,
                "authorizedSigner": self.authorizedSigner,
                "mint": self.mint,
                "rentPayer": self.rentPayer,
                "openSlot": self.openSlot,
                }
    def to_json(self) -> ChannelJSON:
        return {
                "version": self.version,
                "bump": self.bump,
                "status": self.status,
                "salt": self.salt,
                "deposit": self.deposit,
                "settlement": self.settlement.to_json(),
                "closureStartedAt": self.closureStartedAt,
                "payerWithdrawnAt": self.payerWithdrawnAt,
                "gracePeriod": self.gracePeriod,
                "distributionHash": self.distributionHash,
                "payer": str(self.payer),
                "payee": str(self.payee),
                "authorizedSigner": str(self.authorizedSigner),
                "mint": str(self.mint),
                "rentPayer": str(self.rentPayer),
                "openSlot": self.openSlot,
                }

    @classmethod
    def from_json(cls, obj: ChannelJSON) -> "Channel":
        return cls(
                version=obj["version"],
                bump=obj["bump"],
                status=obj["status"],
                salt=obj["salt"],
                deposit=obj["deposit"],
                settlement=types.settlementWatermarks.SettlementWatermarks.from_json(obj["settlement"]),
                closureStartedAt=obj["closureStartedAt"],
                payerWithdrawnAt=obj["payerWithdrawnAt"],
                gracePeriod=obj["gracePeriod"],
                distributionHash=obj["distributionHash"],
                payer=SolPubkey.from_string(obj["payer"]),
                payee=SolPubkey.from_string(obj["payee"]),
                authorizedSigner=SolPubkey.from_string(obj["authorizedSigner"]),
                mint=SolPubkey.from_string(obj["mint"]),
                rentPayer=SolPubkey.from_string(obj["rentPayer"]),
                openSlot=obj["openSlot"],
                )




