'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import PAYMENT_CHANNELS_PROGRAM_ADDRESS
class OpenArgs(typing.TypedDict):
    openArgs:types.openArgs.OpenArgs


layout = borsh.CStruct(
    "openArgs" /types.openArgs.OpenArgs.layout,
    )


class OpenAccounts(typing.TypedDict):
    payer:SolPubkey
    payee:SolPubkey
    mint:SolPubkey
    authorizedSigner:SolPubkey
    channel:SolPubkey
    payerTokenAccount:SolPubkey
    channelTokenAccount:SolPubkey
    tokenProgram:SolPubkey
    systemProgram:SolPubkey
    rent:SolPubkey
    associatedTokenProgram:SolPubkey
    eventAuthority:SolPubkey
    selfProgram:SolPubkey

def Open(
    args: OpenArgs,
    accounts: OpenAccounts,
    program_id: SolPubkey =  PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["payee"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["authorizedSigner"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["channel"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["payerTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["channelTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["rent"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["associatedTokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["eventAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["selfProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x01"


    encoded_args = layout.build({
        "openArgs":args["openArgs"].to_encodable(),
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




def find_EventAuthority() -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"event_authority",
    ]

    address, bump = SolPubkey.find_program_address(seeds,
         PAYMENT_CHANNELS_PROGRAM_ADDRESS
            )

    return address, bump





