'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

from solders.pubkey import Pubkey

PAYMENT_CHANNELS_PROGRAM_ADDRESS =Pubkey.from_string("CQAyft83tN1w2bRofB5PZ79eVDU2xZUVo43LU1qL4zRg")

