-- Luacheck configuration for the Lua MPP SDK.
--
-- The repo skill `skills/pay-sdk-implementation/references/coding-conventions.md`
-- specifies luacheck as the canonical linter for Lua. The settings below match
-- the conventions used across `pay_kit/` and `tests/`:
--
--   - LuaJIT 2.1 is the production runtime target (matches OpenResty / Kong).
--   - Underscore-prefixed identifiers (`_value`, `_unused`) are explicit
--     "I know this is unused" markers; do not warn about them.
--   - The existing test suite uses long descriptive assertion messages; cap
--     the line length at 140 so descriptive code stays readable without
--     forcing artificial line breaks inside table literals.
--   - `error` callbacks raise typed error tables; allow them to be re-raised
--     without being treated as unused.
std = "luajit"
max_line_length = 140
unused_args = false
-- Underscore-prefixed local variables are an explicit "I know this is unused"
-- convention across the SDK and the tests (e.g. `local _ok, _err = pcall(...)`,
-- `local _method_details = ...`). Treat them as ignored everywhere.
ignore = { "211/_.*" }

-- The test runner walks `./?.lua`, `./?/init.lua`, and `./lua/?.lua`. Both
-- entry points are equivalent for luacheck.
files["pay_kit/init.lua"] = {
  -- The SDK entry re-exports many modules; allow the long ASCII table.
  max_line_length = 160,
}

-- The HTML asset rendering inlines a small CSS block with long font-stack and
-- box-shadow declarations that are clearer on one line than wrapped.
files["pay_kit/protocols/mpp/server/html.lua"] = {
  ignore = { "631" }, -- line-too-long
}

-- The HTML assets module is auto-generated by the `html/` package via the
-- payment-link build. Lint it loosely so the generator's output never has
-- to be hand-edited for style compliance.
files["pay_kit/protocols/mpp/server/html_assets/gen.lua"] = {
  ignore = { "631" }, -- line-too-long
}

-- The OpenResty example exposes the `ngx` global at runtime. luacheck does
-- not know about it by default; declare it as a writable global because the
-- access-phase middleware assigns `ngx.status` and `ngx.header[name]`.
-- This lints cleanly without requiring OpenResty's own luacheck plugin.
files["examples/nginx/access.lua"] = {
  globals = { "ngx" },
}

-- The cosocket transport reads `ngx.get_phase()` to refuse running in
-- non-cosocket-capable nginx phases. luacheck does not ship with the
-- OpenResty global set; allowlist the `ngx` global here too.
files["pay_kit/solana/rpc_transport_resty.lua"] = {
  read_globals = { "ngx" },
}

-- The resty-transport spec writes to the `ngx` global to simulate the
-- OpenResty environment for each test case.
files["tests/solana_rpc_transport_resty_spec.lua"] = {
  globals = { "ngx" },
}
