'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class SubscriptionAuthorityJSON(typing.TypedDict):
    kind: typing.Literal["SubscriptionAuthority"]


@dataclass
class SubscriptionAuthority:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> SubscriptionAuthorityJSON:
        return SubscriptionAuthorityJSON(
            kind="SubscriptionAuthority",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "SubscriptionAuthority": {},
        }




class PlanJSON(typing.TypedDict):
    kind: typing.Literal["Plan"]


@dataclass
class Plan:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> PlanJSON:
        return PlanJSON(
            kind="Plan",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Plan": {},
        }




class FixedDelegationJSON(typing.TypedDict):
    kind: typing.Literal["FixedDelegation"]


@dataclass
class FixedDelegation:
    discriminator: typing.ClassVar = 2
    def to_json(self) -> FixedDelegationJSON:
        return FixedDelegationJSON(
            kind="FixedDelegation",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "FixedDelegation": {},
        }




class RecurringDelegationJSON(typing.TypedDict):
    kind: typing.Literal["RecurringDelegation"]


@dataclass
class RecurringDelegation:
    discriminator: typing.ClassVar = 3
    def to_json(self) -> RecurringDelegationJSON:
        return RecurringDelegationJSON(
            kind="RecurringDelegation",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "RecurringDelegation": {},
        }




class SubscriptionDelegationJSON(typing.TypedDict):
    kind: typing.Literal["SubscriptionDelegation"]


@dataclass
class SubscriptionDelegation:
    discriminator: typing.ClassVar = 4
    def to_json(self) -> SubscriptionDelegationJSON:
        return SubscriptionDelegationJSON(
            kind="SubscriptionDelegation",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "SubscriptionDelegation": {},
        }





AccountDiscriminatorKind = typing.Union[
    SubscriptionAuthority,
    Plan,
    FixedDelegation,
    RecurringDelegation,
    SubscriptionDelegation,
]
AccountDiscriminatorJSON = typing.Union[
    SubscriptionAuthorityJSON,
    PlanJSON,
    FixedDelegationJSON,
    RecurringDelegationJSON,
    SubscriptionDelegationJSON,
]

def from_decoded(obj: dict) -> AccountDiscriminatorKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "SubscriptionAuthority" in obj:
      return SubscriptionAuthority()
    if "Plan" in obj:
      return Plan()
    if "FixedDelegation" in obj:
      return FixedDelegation()
    if "RecurringDelegation" in obj:
      return RecurringDelegation()
    if "SubscriptionDelegation" in obj:
      return SubscriptionDelegation()
    raise ValueError("Invalid enum object")

def from_json(obj: AccountDiscriminatorJSON) -> AccountDiscriminatorKind:
    if obj["kind"] == "SubscriptionAuthority":
        return SubscriptionAuthority()

    if obj["kind"] == "Plan":
        return Plan()

    if obj["kind"] == "FixedDelegation":
        return FixedDelegation()

    if obj["kind"] == "RecurringDelegation":
        return RecurringDelegation()

    if obj["kind"] == "SubscriptionDelegation":
        return SubscriptionDelegation()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"SubscriptionAuthority" / borsh.CStruct(),
"Plan" / borsh.CStruct(),
"FixedDelegation" / borsh.CStruct(),
"RecurringDelegation" / borsh.CStruct(),
"SubscriptionDelegation" / borsh.CStruct(),
)
