'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class CancelSubscriptionNowDataJSON(typing.TypedDict):
    expectedCurrentPeriodStartTs: int

@dataclass
class CancelSubscriptionNowData:
    layout: typing.ClassVar = borsh.CStruct(
        "expectedCurrentPeriodStartTs" /borsh.I64,
        )
    #fields
    expectedCurrentPeriodStartTs: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "CancelSubscriptionNowData":
        return cls(
        expectedCurrentPeriodStartTs=obj["expectedCurrentPeriodStartTs"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "expectedCurrentPeriodStartTs": self.expectedCurrentPeriodStartTs,
                }

    def to_json(self) -> CancelSubscriptionNowDataJSON:
        return {
                "expectedCurrentPeriodStartTs": self.expectedCurrentPeriodStartTs,
                }

    @classmethod
    def from_json(cls, obj: CancelSubscriptionNowDataJSON) -> "CancelSubscriptionNowData":
        return cls(
                expectedCurrentPeriodStartTs=obj["expectedCurrentPeriodStartTs"],
        )






