'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class CreateRecurringDelegationDataJSON(typing.TypedDict):
    nonce: int
    amountPerPeriod: int
    periodLengthS: int
    startTs: int
    expiryTs: int
    expectedSubscriptionAuthorityInitId: int

@dataclass
class CreateRecurringDelegationData:
    layout: typing.ClassVar = borsh.CStruct(
        "nonce" /borsh.U64,
        "amountPerPeriod" /borsh.U64,
        "periodLengthS" /borsh.U64,
        "startTs" /borsh.I64,
        "expiryTs" /borsh.I64,
        "expectedSubscriptionAuthorityInitId" /borsh.I64,
        )
    #fields
    nonce: int
    amountPerPeriod: int
    periodLengthS: int
    startTs: int
    expiryTs: int
    expectedSubscriptionAuthorityInitId: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "CreateRecurringDelegationData":
        return cls(
        nonce=obj["nonce"],
        amountPerPeriod=obj["amountPerPeriod"],
        periodLengthS=obj["periodLengthS"],
        startTs=obj["startTs"],
        expiryTs=obj["expiryTs"],
        expectedSubscriptionAuthorityInitId=obj["expectedSubscriptionAuthorityInitId"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "nonce": self.nonce,
                "amountPerPeriod": self.amountPerPeriod,
                "periodLengthS": self.periodLengthS,
                "startTs": self.startTs,
                "expiryTs": self.expiryTs,
                "expectedSubscriptionAuthorityInitId": self.expectedSubscriptionAuthorityInitId,
                }

    def to_json(self) -> CreateRecurringDelegationDataJSON:
        return {
                "nonce": self.nonce,
                "amountPerPeriod": self.amountPerPeriod,
                "periodLengthS": self.periodLengthS,
                "startTs": self.startTs,
                "expiryTs": self.expiryTs,
                "expectedSubscriptionAuthorityInitId": self.expectedSubscriptionAuthorityInitId,
                }

    @classmethod
    def from_json(cls, obj: CreateRecurringDelegationDataJSON) -> "CreateRecurringDelegationData":
        return cls(
                nonce=obj["nonce"],
                amountPerPeriod=obj["amountPerPeriod"],
                periodLengthS=obj["periodLengthS"],
                startTs=obj["startTs"],
                expiryTs=obj["expiryTs"],
                expectedSubscriptionAuthorityInitId=obj["expectedSubscriptionAuthorityInitId"],
        )






