'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class CreateFixedDelegationDataJSON(typing.TypedDict):
    nonce: int
    amount: int
    expiryTs: int
    expectedSubscriptionAuthorityInitId: int

@dataclass
class CreateFixedDelegationData:
    layout: typing.ClassVar = borsh.CStruct(
        "nonce" /borsh.U64,
        "amount" /borsh.U64,
        "expiryTs" /borsh.I64,
        "expectedSubscriptionAuthorityInitId" /borsh.I64,
        )
    #fields
    nonce: int
    amount: int
    expiryTs: int
    expectedSubscriptionAuthorityInitId: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "CreateFixedDelegationData":
        return cls(
        nonce=obj["nonce"],
        amount=obj["amount"],
        expiryTs=obj["expiryTs"],
        expectedSubscriptionAuthorityInitId=obj["expectedSubscriptionAuthorityInitId"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "nonce": self.nonce,
                "amount": self.amount,
                "expiryTs": self.expiryTs,
                "expectedSubscriptionAuthorityInitId": self.expectedSubscriptionAuthorityInitId,
                }

    def to_json(self) -> CreateFixedDelegationDataJSON:
        return {
                "nonce": self.nonce,
                "amount": self.amount,
                "expiryTs": self.expiryTs,
                "expectedSubscriptionAuthorityInitId": self.expectedSubscriptionAuthorityInitId,
                }

    @classmethod
    def from_json(cls, obj: CreateFixedDelegationDataJSON) -> "CreateFixedDelegationData":
        return cls(
                nonce=obj["nonce"],
                amount=obj["amount"],
                expiryTs=obj["expiryTs"],
                expectedSubscriptionAuthorityInitId=obj["expectedSubscriptionAuthorityInitId"],
        )






