'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class HeaderJSON(typing.TypedDict):
    version: int
    bump: int
    delegator: str
    delegatee: str
    payer: str
    initId: int

@dataclass
class Header:
    layout: typing.ClassVar = borsh.CStruct(
        "version" /borsh.U8,
        "bump" /borsh.U8,
        "delegator" /BorshPubkey,
        "delegatee" /BorshPubkey,
        "payer" /BorshPubkey,
        "initId" /borsh.I64,
        )
    #fields
    version: int
    bump: int
    delegator: SolPubkey
    delegatee: SolPubkey
    payer: SolPubkey
    initId: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "Header":
        return cls(
        version=obj["version"],
        bump=obj["bump"],
        delegator=obj["delegator"],
        delegatee=obj["delegatee"],
        payer=obj["payer"],
        initId=obj["initId"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "version": self.version,
                "bump": self.bump,
                "delegator": self.delegator,
                "delegatee": self.delegatee,
                "payer": self.payer,
                "initId": self.initId,
                }

    def to_json(self) -> HeaderJSON:
        return {
                "version": self.version,
                "bump": self.bump,
                "delegator": str(self.delegator),
                "delegatee": str(self.delegatee),
                "payer": str(self.payer),
                "initId": self.initId,
                }

    @classmethod
    def from_json(cls, obj: HeaderJSON) -> "Header":
        return cls(
                version=obj["version"],
                bump=obj["bump"],
                delegator=SolPubkey.from_string(obj["delegator"]),
                delegatee=SolPubkey.from_string(obj["delegatee"]),
                payer=SolPubkey.from_string(obj["payer"]),
                initId=obj["initId"],
        )






