'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class SunsetJSON(typing.TypedDict):
    kind: typing.Literal["Sunset"]


@dataclass
class Sunset:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> SunsetJSON:
        return SunsetJSON(
            kind="Sunset",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Sunset": {},
        }




class ActiveJSON(typing.TypedDict):
    kind: typing.Literal["Active"]


@dataclass
class Active:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> ActiveJSON:
        return ActiveJSON(
            kind="Active",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Active": {},
        }





PlanStatusKind = typing.Union[
    Sunset,
    Active,
]
PlanStatusJSON = typing.Union[
    SunsetJSON,
    ActiveJSON,
]

def from_decoded(obj: dict) -> PlanStatusKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "Sunset" in obj:
      return Sunset()
    if "Active" in obj:
      return Active()
    raise ValueError("Invalid enum object")

def from_json(obj: PlanStatusJSON) -> PlanStatusKind:
    if obj["kind"] == "Sunset":
        return Sunset()

    if obj["kind"] == "Active":
        return Active()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"Sunset" / borsh.CStruct(),
"Active" / borsh.CStruct(),
)
