'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class PlanTermsJSON(typing.TypedDict):
    amount: int
    periodHours: int
    createdAt: int

@dataclass
class PlanTerms:
    layout: typing.ClassVar = borsh.CStruct(
        "amount" /borsh.U64,
        "periodHours" /borsh.U64,
        "createdAt" /borsh.I64,
        )
    #fields
    amount: int
    periodHours: int
    createdAt: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "PlanTerms":
        return cls(
        amount=obj["amount"],
        periodHours=obj["periodHours"],
        createdAt=obj["createdAt"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "amount": self.amount,
                "periodHours": self.periodHours,
                "createdAt": self.createdAt,
                }

    def to_json(self) -> PlanTermsJSON:
        return {
                "amount": self.amount,
                "periodHours": self.periodHours,
                "createdAt": self.createdAt,
                }

    @classmethod
    def from_json(cls, obj: PlanTermsJSON) -> "PlanTerms":
        return cls(
                amount=obj["amount"],
                periodHours=obj["periodHours"],
                createdAt=obj["createdAt"],
        )






