'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey
from . import planTerms
from ..shared import FixedSizeString

class PlanDataJSON(typing.TypedDict):
    planId: int
    mint: str
    terms: planTerms.PlanTermsJSON
    endTs: int
    destinations: list[str]
    pullers: list[str]
    metadataUri: list[int]

@dataclass
class PlanData:
    layout: typing.ClassVar = borsh.CStruct(
        "planId" /borsh.U64,
        "mint" /BorshPubkey,
        "terms" /planTerms.PlanTerms.layout,
        "endTs" /borsh.I64,
        "destinations" /BorshPubkey[4],
        "pullers" /BorshPubkey[4],
        "metadataUri" /FixedSizeString(128,"utf8"),
        )
    #fields
    planId: int
    mint: SolPubkey
    terms: planTerms.PlanTerms
    endTs: int
    destinations: list[SolPubkey]
    pullers: list[SolPubkey]
    metadataUri: list[int]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "PlanData":
        return cls(
        planId=obj["planId"],
        mint=obj["mint"],
        terms=planTerms.PlanTerms.from_decoded(obj["terms"]),
        endTs=obj["endTs"],
        destinations=obj["destinations"],
        pullers=obj["pullers"],
        metadataUri=obj["metadataUri"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "planId": self.planId,
                "mint": self.mint,
                "terms": self.terms.to_encodable(),
                "endTs": self.endTs,
                "destinations": self.destinations,
                "pullers": self.pullers,
                "metadataUri": self.metadataUri,
                }

    def to_json(self) -> PlanDataJSON:
        return {
                "planId": self.planId,
                "mint": str(self.mint),
                "terms": self.terms.to_json(),
                "endTs": self.endTs,
                "destinations": list(map(lambda item:str(item),self.destinations)),
                "pullers": list(map(lambda item:str(item),self.pullers)),
                "metadataUri": self.metadataUri,
                }

    @classmethod
    def from_json(cls, obj: PlanDataJSON) -> "PlanData":
        return cls(
                planId=obj["planId"],
                mint=SolPubkey.from_string(obj["mint"]),
                terms=planTerms.PlanTerms.from_json(obj["terms"]),
                endTs=obj["endTs"],
                destinations=list(map(lambda item:SolPubkey.from_string(item),obj["destinations"])),
                pullers=list(map(lambda item:SolPubkey.from_string(item),obj["pullers"])),
                metadataUri=obj["metadataUri"],
        )






