'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class ResumeDataJSON(typing.TypedDict):
    expectedExpiresAtTs: int

@dataclass
class ResumeData:
    layout: typing.ClassVar = borsh.CStruct(
        "expectedExpiresAtTs" /borsh.I64,
        )
    #fields
    expectedExpiresAtTs: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "ResumeData":
        return cls(
        expectedExpiresAtTs=obj["expectedExpiresAtTs"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "expectedExpiresAtTs": self.expectedExpiresAtTs,
                }

    def to_json(self) -> ResumeDataJSON:
        return {
                "expectedExpiresAtTs": self.expectedExpiresAtTs,
                }

    @classmethod
    def from_json(cls, obj: ResumeDataJSON) -> "ResumeData":
        return cls(
                expectedExpiresAtTs=obj["expectedExpiresAtTs"],
        )






