'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class SubscribeDataJSON(typing.TypedDict):
    planId: int
    planBump: int
    expectedMint: str
    expectedAmount: int
    expectedPeriodHours: int
    expectedCreatedAt: int
    expectedSubscriptionAuthorityInitId: int

@dataclass
class SubscribeData:
    layout: typing.ClassVar = borsh.CStruct(
        "planId" /borsh.U64,
        "planBump" /borsh.U8,
        "expectedMint" /BorshPubkey,
        "expectedAmount" /borsh.U64,
        "expectedPeriodHours" /borsh.U64,
        "expectedCreatedAt" /borsh.I64,
        "expectedSubscriptionAuthorityInitId" /borsh.I64,
        )
    #fields
    planId: int
    planBump: int
    expectedMint: SolPubkey
    expectedAmount: int
    expectedPeriodHours: int
    expectedCreatedAt: int
    expectedSubscriptionAuthorityInitId: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "SubscribeData":
        return cls(
        planId=obj["planId"],
        planBump=obj["planBump"],
        expectedMint=obj["expectedMint"],
        expectedAmount=obj["expectedAmount"],
        expectedPeriodHours=obj["expectedPeriodHours"],
        expectedCreatedAt=obj["expectedCreatedAt"],
        expectedSubscriptionAuthorityInitId=obj["expectedSubscriptionAuthorityInitId"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "planId": self.planId,
                "planBump": self.planBump,
                "expectedMint": self.expectedMint,
                "expectedAmount": self.expectedAmount,
                "expectedPeriodHours": self.expectedPeriodHours,
                "expectedCreatedAt": self.expectedCreatedAt,
                "expectedSubscriptionAuthorityInitId": self.expectedSubscriptionAuthorityInitId,
                }

    def to_json(self) -> SubscribeDataJSON:
        return {
                "planId": self.planId,
                "planBump": self.planBump,
                "expectedMint": str(self.expectedMint),
                "expectedAmount": self.expectedAmount,
                "expectedPeriodHours": self.expectedPeriodHours,
                "expectedCreatedAt": self.expectedCreatedAt,
                "expectedSubscriptionAuthorityInitId": self.expectedSubscriptionAuthorityInitId,
                }

    @classmethod
    def from_json(cls, obj: SubscribeDataJSON) -> "SubscribeData":
        return cls(
                planId=obj["planId"],
                planBump=obj["planBump"],
                expectedMint=SolPubkey.from_string(obj["expectedMint"]),
                expectedAmount=obj["expectedAmount"],
                expectedPeriodHours=obj["expectedPeriodHours"],
                expectedCreatedAt=obj["expectedCreatedAt"],
                expectedSubscriptionAuthorityInitId=obj["expectedSubscriptionAuthorityInitId"],
        )






