'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class TransferDataJSON(typing.TypedDict):
    amount: int
    delegator: str
    mint: str

@dataclass
class TransferData:
    layout: typing.ClassVar = borsh.CStruct(
        "amount" /borsh.U64,
        "delegator" /BorshPubkey,
        "mint" /BorshPubkey,
        )
    #fields
    amount: int
    delegator: SolPubkey
    mint: SolPubkey
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "TransferData":
        return cls(
        amount=obj["amount"],
        delegator=obj["delegator"],
        mint=obj["mint"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "amount": self.amount,
                "delegator": self.delegator,
                "mint": self.mint,
                }

    def to_json(self) -> TransferDataJSON:
        return {
                "amount": self.amount,
                "delegator": str(self.delegator),
                "mint": str(self.mint),
                }

    @classmethod
    def from_json(cls, obj: TransferDataJSON) -> "TransferData":
        return cls(
                amount=obj["amount"],
                delegator=SolPubkey.from_string(obj["delegator"]),
                mint=SolPubkey.from_string(obj["mint"]),
        )






