'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey
from ..shared import FixedSizeString

class UpdatePlanDataJSON(typing.TypedDict):
    status: int
    endTs: int
    pullers: list[str]
    metadataUri: list[int]
    expectedCreatedAt: int
    expectedEndTs: int
    expectedPullers: list[str]
    expectedMetadataUri: list[int]

@dataclass
class UpdatePlanData:
    layout: typing.ClassVar = borsh.CStruct(
        "status" /borsh.U8,
        "endTs" /borsh.I64,
        "pullers" /BorshPubkey[4],
        "metadataUri" /FixedSizeString(128,"utf8"),
        "expectedCreatedAt" /borsh.I64,
        "expectedEndTs" /borsh.I64,
        "expectedPullers" /BorshPubkey[4],
        "expectedMetadataUri" /FixedSizeString(128,"utf8"),
        )
    #fields
    status: int
    endTs: int
    pullers: list[SolPubkey]
    metadataUri: list[int]
    expectedCreatedAt: int
    expectedEndTs: int
    expectedPullers: list[SolPubkey]
    expectedMetadataUri: list[int]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "UpdatePlanData":
        return cls(
        status=obj["status"],
        endTs=obj["endTs"],
        pullers=obj["pullers"],
        metadataUri=obj["metadataUri"],
        expectedCreatedAt=obj["expectedCreatedAt"],
        expectedEndTs=obj["expectedEndTs"],
        expectedPullers=obj["expectedPullers"],
        expectedMetadataUri=obj["expectedMetadataUri"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "status": self.status,
                "endTs": self.endTs,
                "pullers": self.pullers,
                "metadataUri": self.metadataUri,
                "expectedCreatedAt": self.expectedCreatedAt,
                "expectedEndTs": self.expectedEndTs,
                "expectedPullers": self.expectedPullers,
                "expectedMetadataUri": self.expectedMetadataUri,
                }

    def to_json(self) -> UpdatePlanDataJSON:
        return {
                "status": self.status,
                "endTs": self.endTs,
                "pullers": list(map(lambda item:str(item),self.pullers)),
                "metadataUri": self.metadataUri,
                "expectedCreatedAt": self.expectedCreatedAt,
                "expectedEndTs": self.expectedEndTs,
                "expectedPullers": list(map(lambda item:str(item),self.expectedPullers)),
                "expectedMetadataUri": self.expectedMetadataUri,
                }

    @classmethod
    def from_json(cls, obj: UpdatePlanDataJSON) -> "UpdatePlanData":
        return cls(
                status=obj["status"],
                endTs=obj["endTs"],
                pullers=list(map(lambda item:SolPubkey.from_string(item),obj["pullers"])),
                metadataUri=obj["metadataUri"],
                expectedCreatedAt=obj["expectedCreatedAt"],
                expectedEndTs=obj["expectedEndTs"],
                expectedPullers=list(map(lambda item:SolPubkey.from_string(item),obj["expectedPullers"])),
                expectedMetadataUri=obj["expectedMetadataUri"],
        )






