'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS
class CreateRecurringDelegationArgs(typing.TypedDict):
    recurringDelegation:types.createRecurringDelegationData.CreateRecurringDelegationData


layout = borsh.CStruct(
    "recurringDelegation" /types.createRecurringDelegationData.CreateRecurringDelegationData.layout,
    )


class CreateRecurringDelegationAccounts(typing.TypedDict):
    delegator:SolPubkey
    subscriptionAuthority:SolPubkey
    delegationAccount:SolPubkey
    delegatee:SolPubkey
    systemProgram:SolPubkey
    payer:SolPubkey

def CreateRecurringDelegation(
    args: CreateRecurringDelegationArgs,
    accounts: CreateRecurringDelegationAccounts,
    program_id: SolPubkey =  SUBSCRIPTIONS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["delegator"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["subscriptionAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["delegationAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["delegatee"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x02"


    encoded_args = layout.build({
        "recurringDelegation":args["recurringDelegation"].to_encodable(),
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




