'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS

class RevokeAbandonedSubscriptionAccounts(typing.TypedDict):
    payer:SolPubkey
    subscriptionAccount:SolPubkey
    subscriptionAuthority:SolPubkey
    planPda:SolPubkey

def RevokeAbandonedSubscription(
    accounts: RevokeAbandonedSubscriptionAccounts,
    program_id: SolPubkey =  SUBSCRIPTIONS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["subscriptionAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["subscriptionAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["planPda"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x10"


    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



