'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS

class RevokeSubscriptionAuthorityAccounts(typing.TypedDict):
    user:SolPubkey
    userAta:SolPubkey
    tokenMint:SolPubkey
    tokenProgram:SolPubkey
    subscriptionAuthority:SolPubkey
    receiver:SolPubkey

def RevokeSubscriptionAuthority(
    accounts: RevokeSubscriptionAuthorityAccounts,
    program_id: SolPubkey =  SUBSCRIPTIONS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["user"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["userAta"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["tokenMint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["subscriptionAuthority"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["receiver"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x0e"


    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)


def find_SubscriptionAuthority(user: SolPubkey, tokenMint: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"SubscriptionAuthority",
       bytes(user),
       bytes(tokenMint),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
         SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump



