'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS
class SubscribeArgs(typing.TypedDict):
    subscribeData:types.subscribeData.SubscribeData


layout = borsh.CStruct(
    "subscribeData" /types.subscribeData.SubscribeData.layout,
    )


class SubscribeAccounts(typing.TypedDict):
    subscriber:SolPubkey
    merchant:SolPubkey
    planPda:SolPubkey
    subscriptionPda:SolPubkey
    subscriptionAuthorityPda:SolPubkey
    systemProgram:SolPubkey
    eventAuthority:SolPubkey
    selfProgram:SolPubkey
    payer:SolPubkey

def Subscribe(
    args: SubscribeArgs,
    accounts: SubscribeAccounts,
    program_id: SolPubkey =  SUBSCRIPTIONS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["subscriber"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["merchant"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["planPda"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["subscriptionPda"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["subscriptionAuthorityPda"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["eventAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["selfProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x0b"


    encoded_args = layout.build({
        "subscribeData":args["subscribeData"].to_encodable(),
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)


def find_SubscriptionPda(planPda: SolPubkey, subscriber: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"subscription",
       bytes(planPda),
       bytes(subscriber),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
         SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump





def find_EventAuthority() -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"event_authority",
    ]

    address, bump = SolPubkey.find_program_address(seeds,
         SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump





