'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS
class UpdatePlanArgs(typing.TypedDict):
    updatePlanData:types.updatePlanData.UpdatePlanData


layout = borsh.CStruct(
    "updatePlanData" /types.updatePlanData.UpdatePlanData.layout,
    )


class UpdatePlanAccounts(typing.TypedDict):
    owner:SolPubkey
    planPda:SolPubkey
    eventAuthority:SolPubkey
    selfProgram:SolPubkey

def UpdatePlan(
    args: UpdatePlanArgs,
    accounts: UpdatePlanAccounts,
    program_id: SolPubkey =  SUBSCRIPTIONS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["owner"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["planPda"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["eventAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["selfProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x08"


    encoded_args = layout.build({
        "updatePlanData":args["updatePlanData"].to_encodable(),
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)


def find_EventAuthority() -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"event_authority",
    ]

    address, bump = SolPubkey.find_program_address(seeds,
         SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump





