import Foundation
import Testing
@testable import SolanaPayKit

/// Golden vectors generated by a local Rust binary against `bs58 = "0.5"`,
/// the exact crate version pinned in `rust/Cargo.toml`. Any divergence
/// here means the Swift implementation does not agree with the Rust
/// spine on the wire.
@Suite("Base58 parity with Rust bs58 0.5")
struct Base58Tests {
    struct Vector {
        let label: String
        let hex: String
        let base58: String
    }

    static let vectors: [Vector] = [
        Vector(label: "empty", hex: "", base58: ""),
        Vector(label: "one_zero", hex: "00", base58: "1"),
        Vector(label: "two_zero", hex: "0000", base58: "11"),
        Vector(label: "three_zero_one", hex: "000001", base58: "112"),
        Vector(
            label: "system_program_32_zeros",
            hex: "0000000000000000000000000000000000000000000000000000000000000000",
            base58: "11111111111111111111111111111111"
        ),
        Vector(
            label: "usdc_mint",
            hex: "c6fa7af3bedbad3a3d65f36aabc97431b1bbe4c2d2f6e0e47ca60203452f5d61",
            base58: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        ),
        Vector(
            label: "token_program",
            hex: "06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9",
            base58: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        ),
        Vector(
            label: "seq_0_31",
            hex: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
            base58: "1thX6LZfHDZZKUs92febYZhYRcXddmzfzF2NvTkPNE"
        ),
        Vector(
            label: "seq_255_only",
            hex: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
            base58: "JEKNVnkbo3jma5nREBBJCDoXFVeKkD56V3xKrvRmWxFG"
        ),
        Vector(label: "ff", hex: "ff", base58: "5Q"),
        Vector(label: "ff_ff", hex: "ffff", base58: "LUv"),
        Vector(label: "hello", hex: "48656c6c6f20576f726c6421", base58: "2NEpo7TZRRrLZSi2U"),
        Vector(label: "byte_61", hex: "3d", base58: "24"),
        Vector(label: "zero_then_payload", hex: "00801a", base58: "1AkR"),
    ]

    @Test
    func encodesEachVectorIdenticallyToRust() throws {
        for vector in Self.vectors {
            let data = try TestHex.decode(vector.hex)
            #expect(
                Base58.encode(data) == vector.base58,
                "encode mismatch for \(vector.label)"
            )
        }
    }

    @Test
    func decodesEachVectorIdenticallyToRust() throws {
        for vector in Self.vectors {
            let expected = try TestHex.decode(vector.hex)
            let got = try Base58.decode(vector.base58)
            #expect(got == expected, "decode mismatch for \(vector.label)")
        }
    }

    @Test
    func roundTripsRandomBytes() throws {
        for _ in 0..<32 {
            let length = Int.random(in: 0..<33)
            var bytes = [UInt8]()
            bytes.reserveCapacity(length)
            for _ in 0..<length { bytes.append(UInt8.random(in: 0...UInt8.max)) }
            let data = Data(bytes)
            let encoded = Base58.encode(data)
            let decoded = try Base58.decode(encoded)
            #expect(decoded == data, "round trip failed for \(data as NSData)")
        }
    }

    @Test
    func rejectsInvalidCharacters() {
        #expect(throws: MppError.invalidBase58) {
            _ = try Base58.decode("0OIl")
        }
        #expect(throws: MppError.invalidBase58) {
            _ = try Base58.decode("not~ascii")
        }
    }
}

enum TestHex {
    static func decode(_ string: String) throws -> Data {
        if string.isEmpty { return Data() }
        guard string.count % 2 == 0 else {
            throw MppError.invalidJSON("odd-length hex string")
        }
        var bytes = [UInt8]()
        bytes.reserveCapacity(string.count / 2)
        var index = string.startIndex
        while index < string.endIndex {
            let next = string.index(index, offsetBy: 2)
            guard let byte = UInt8(string[index..<next], radix: 16) else {
                throw MppError.invalidJSON("bad hex byte")
            }
            bytes.append(byte)
            index = next
        }
        return Data(bytes)
    }
}
