import Foundation
import Testing
@testable import SolanaPayKit

/// Golden vectors generated by a Rust binary against `solana-message`
/// 3.1.0, the same crate the spine pins in `rust/Cargo.toml`. The
/// fixture pubkeys are deterministic (single-byte payloads at index 31
/// so we can build them in both languages from a Pubkey-of-byte
/// helper).
@Suite("Transaction codec parity with Rust solana-message 3.1")
struct TransactionTests {
    static func pubkeyOf(_ byte: UInt8) -> Pubkey {
        var bytes = Data(repeating: 0, count: 32)
        bytes[31] = byte
        return try! Pubkey(bytes: bytes)
    }

    static var blockhash: Data {
        Data(repeating: 0x09, count: 32)
    }

    @Test
    func legacySolTransferMatchesRust() throws {
        let payer = Self.pubkeyOf(1)
        let recipient = Self.pubkeyOf(2)
        let system = Self.pubkeyOf(0)

        var data = Data()
        data.append(contentsOf: withUnsafeBytes(of: UInt32(2).littleEndian, Array.init))
        data.append(contentsOf: withUnsafeBytes(of: UInt64(1000).littleEndian, Array.init))

        let ix = SolanaInstruction(
            programId: system,
            accounts: [
                .writableSigner(payer),
                .writable(recipient),
            ],
            data: data
        )

        let message = try TransactionBuilder.compile(
            version: .legacy,
            feePayer: payer,
            instructions: [ix],
            recentBlockhash: Self.blockhash
        )
        let bytes = message.serialize()

        let expected = "01000103000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000090909090909090909090909090909090909090909090909090909090909090901020200010c02000000e803000000000000"

        #expect(TestHex.encode(bytes) == expected)
    }

    @Test
    func v0SolTransferMatchesRust() throws {
        let payer = Self.pubkeyOf(1)
        let recipient = Self.pubkeyOf(2)
        let system = Self.pubkeyOf(0)

        var data = Data()
        data.append(contentsOf: withUnsafeBytes(of: UInt32(2).littleEndian, Array.init))
        data.append(contentsOf: withUnsafeBytes(of: UInt64(1000).littleEndian, Array.init))

        let ix = SolanaInstruction(
            programId: system,
            accounts: [
                .writableSigner(payer),
                .writable(recipient),
            ],
            data: data
        )

        let message = try TransactionBuilder.compile(
            version: .v0,
            feePayer: payer,
            instructions: [ix],
            recentBlockhash: Self.blockhash
        )
        let bytes = message.serialize()

        let expected = "8001000103000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000090909090909090909090909090909090909090909090909090909090909090901020200010c02000000e80300000000000000"

        #expect(TestHex.encode(bytes) == expected)
    }

    @Test
    func v0SplTransferCheckedMatchesRust() throws {
        let payer = Self.pubkeyOf(1)
        let mint = Self.pubkeyOf(10)
        let sourceAta = Self.pubkeyOf(20)
        let destAta = Self.pubkeyOf(30)
        let tokenProgram = Self.pubkeyOf(50)

        var data = Data([12])
        data.append(contentsOf: withUnsafeBytes(of: UInt64(500).littleEndian, Array.init))
        data.append(6)

        let ix = SolanaInstruction(
            programId: tokenProgram,
            accounts: [
                .writable(sourceAta),
                .readonly(mint),
                .writable(destAta),
                .readonlySigner(payer),
            ],
            data: data
        )

        let message = try TransactionBuilder.compile(
            version: .v0,
            feePayer: payer,
            instructions: [ix],
            recentBlockhash: Self.blockhash
        )
        let bytes = message.serialize()

        let expected = "800100020500000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000320909090909090909090909090909090909090909090909090909090909090909010404010302000a0cf4010000000000000600"

        #expect(TestHex.encode(bytes) == expected)
    }

    @Test
    func v0MultiInstructionWithComputeBudgetMatchesRust() throws {
        let payer = Self.pubkeyOf(1)
        let recipient = Self.pubkeyOf(2)
        let system = Self.pubkeyOf(0)
        let computeBudget = Self.pubkeyOf(99)

        var transferData = Data()
        transferData.append(contentsOf: withUnsafeBytes(of: UInt32(2).littleEndian, Array.init))
        transferData.append(contentsOf: withUnsafeBytes(of: UInt64(1000).littleEndian, Array.init))
        let transferIx = SolanaInstruction(
            programId: system,
            accounts: [
                .writableSigner(payer),
                .writable(recipient),
            ],
            data: transferData
        )

        var cbLimitData = Data([2])
        cbLimitData.append(contentsOf: withUnsafeBytes(of: UInt32(200_000).littleEndian, Array.init))
        let cbLimitIx = SolanaInstruction(
            programId: computeBudget,
            accounts: [],
            data: cbLimitData
        )

        var cbPriceData = Data([3])
        cbPriceData.append(contentsOf: withUnsafeBytes(of: UInt64(1).littleEndian, Array.init))
        let cbPriceIx = SolanaInstruction(
            programId: computeBudget,
            accounts: [],
            data: cbPriceData
        )

        let message = try TransactionBuilder.compile(
            version: .v0,
            feePayer: payer,
            instructions: [cbPriceIx, cbLimitIx, transferIx],
            recentBlockhash: Self.blockhash
        )
        let bytes = message.serialize()

        let expected = "8001000204000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006309090909090909090909090909090909090909090909090909090909090909090303000903010000000000000003000502400d0300020200010c02000000e80300000000000000"

        #expect(TestHex.encode(bytes) == expected)
    }

    @Test
    func shortVecEncodesAllBoundaries() {
        #expect(ShortVec.encodeLength(0) == Data([0]))
        #expect(ShortVec.encodeLength(127) == Data([127]))
        #expect(ShortVec.encodeLength(128) == Data([0x80, 1]))
        #expect(ShortVec.encodeLength(16383) == Data([0xff, 127]))
        #expect(ShortVec.encodeLength(16384) == Data([0x80, 0x80, 1]))
        #expect(ShortVec.encodeLength(65535) == Data([0xff, 0xff, 3]))
    }

    @Test
    func signedTransactionPrependsCompactArrayOfSignatures() throws {
        let payer = Self.pubkeyOf(1)
        let recipient = Self.pubkeyOf(2)
        let system = Self.pubkeyOf(0)
        var data = Data()
        data.append(contentsOf: withUnsafeBytes(of: UInt32(2).littleEndian, Array.init))
        data.append(contentsOf: withUnsafeBytes(of: UInt64(1000).littleEndian, Array.init))
        let ix = SolanaInstruction(
            programId: system,
            accounts: [.writableSigner(payer), .writable(recipient)],
            data: data
        )
        let message = try TransactionBuilder.compile(
            version: .legacy,
            feePayer: payer,
            instructions: [ix],
            recentBlockhash: Self.blockhash
        )

        let sig = Data(repeating: 0xAB, count: 64)
        let signed = try SignedTransaction(signatures: [sig], message: message)
        let bytes = signed.serialize()

        // Compact-array prefix is 0x01, then 64 bytes of 0xAB, then the
        // legacy message bytes from the parity test.
        #expect(bytes[0] == 0x01)
        let sigStart = 1
        let sigEnd = 1 + 64
        #expect(bytes.subdata(in: sigStart..<sigEnd) == sig)
        #expect(bytes.subdata(in: sigEnd..<bytes.count) == message.serialize())
    }
}

extension TestHex {
    static func encode(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }
}
