'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PAYMENT_CHANNELS_PROGRAM_ADDRESS


class ClosedChannelJSON(typing.TypedDict):
    pass

@dataclass
class ClosedChannel:
    #fields



    layout: typing.ClassVar = borsh.CStruct(
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    ) -> typing.Optional["ClosedChannel"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    ) -> typing.List[typing.Optional["ClosedChannel"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["ClosedChannel"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "ClosedChannel":
        dec = ClosedChannel.layout.parse(data)
        return cls(
                )
    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                }
    def to_json(self) -> ClosedChannelJSON:
        return {
                }

    @classmethod
    def from_json(cls, obj: ClosedChannelJSON) -> "ClosedChannel":
        return cls(
                )




