'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.pubkey import Pubkey as SolPubkey
from solana.rpc.core import RPCException
from anchorpy.error import extract_code_and_logs

from . import subscriptions
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS

def from_tx_error(
    error: RPCException,
) -> typing.Optional[subscriptions.CustomError]:
    err_info = error.args[0]
    extracted = extract_code_and_logs(err_info, SUBSCRIPTIONS_PROGRAM_ADDRESS)
    if extracted is None:
        return None
    return subscriptions.from_code(extracted[0])
