'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from anchorpy.error import ProgramError

class NotSigner(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            100, ""
        )

    code = 100
    name = "NotSigner"
    msg = ""
class InvalidAddress(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            101, ""
        )

    code = 101
    name = "InvalidAddress"
    msg = ""
class InvalidEscrowPda(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            102, ""
        )

    code = 102
    name = "InvalidEscrowPda"
    msg = ""
class InvalidSubscriptionAuthorityPda(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            103, ""
        )

    code = 103
    name = "InvalidSubscriptionAuthorityPda"
    msg = ""
class NotSystemProgram(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            104, ""
        )

    code = 104
    name = "NotSystemProgram"
    msg = ""
class InvalidTokenProgram(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            105, ""
        )

    code = 105
    name = "InvalidTokenProgram"
    msg = ""
class InvalidToken2022MintAccountData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            106, ""
        )

    code = 106
    name = "InvalidToken2022MintAccountData"
    msg = ""
class InvalidToken2022TokenAccountData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            107, ""
        )

    code = 107
    name = "InvalidToken2022TokenAccountData"
    msg = ""
class InvalidAssociatedTokenAccountDerivedAddress(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            108, ""
        )

    code = 108
    name = "InvalidAssociatedTokenAccountDerivedAddress"
    msg = ""
class InvalidTokenSplMintAccountData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            109, ""
        )

    code = 109
    name = "InvalidTokenSplMintAccountData"
    msg = ""
class InvalidTokenSplTokenAccountData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            110, ""
        )

    code = 110
    name = "InvalidTokenSplTokenAccountData"
    msg = ""
class InvalidAccountData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            111, ""
        )

    code = 111
    name = "InvalidAccountData"
    msg = ""
class InvalidInstructionData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            112, ""
        )

    code = 112
    name = "InvalidInstructionData"
    msg = ""
class NotEnoughAccountKeys(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            113, ""
        )

    code = 113
    name = "NotEnoughAccountKeys"
    msg = ""
class InvalidInstruction(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            114, ""
        )

    code = 114
    name = "InvalidInstruction"
    msg = ""
class ArithmeticOverflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            115, ""
        )

    code = 115
    name = "ArithmeticOverflow"
    msg = ""
class ArithmeticUnderflow(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            116, ""
        )

    code = 116
    name = "ArithmeticUnderflow"
    msg = ""
class InvalidAccountDiscriminator(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            117, ""
        )

    code = 117
    name = "InvalidAccountDiscriminator"
    msg = ""
class MintHasConfidentialTransfer(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            118, ""
        )

    code = 118
    name = "MintHasConfidentialTransfer"
    msg = ""
class MintHasNonTransferable(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            119, ""
        )

    code = 119
    name = "MintHasNonTransferable"
    msg = ""
class MintHasPermanentDelegate(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            120, ""
        )

    code = 120
    name = "MintHasPermanentDelegate"
    msg = ""
class MintHasTransferHook(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            121, ""
        )

    code = 121
    name = "MintHasTransferHook"
    msg = ""
class MintHasTransferFee(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            122, ""
        )

    code = 122
    name = "MintHasTransferFee"
    msg = ""
class MintHasMintCloseAuthority(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            123, ""
        )

    code = 123
    name = "MintHasMintCloseAuthority"
    msg = ""
class MintHasPausable(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            124, ""
        )

    code = 124
    name = "MintHasPausable"
    msg = ""
class MintMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            125, ""
        )

    code = 125
    name = "MintMismatch"
    msg = ""
class InvalidDelegatePda(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            126, ""
        )

    code = 126
    name = "InvalidDelegatePda"
    msg = ""
class InvalidHeaderData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            127, ""
        )

    code = 127
    name = "InvalidHeaderData"
    msg = ""
class DelegationExpired(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            128, ""
        )

    code = 128
    name = "DelegationExpired"
    msg = ""
class InvalidAmount(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            129, ""
        )

    code = 129
    name = "InvalidAmount"
    msg = ""
class Unauthorized(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            130, ""
        )

    code = 130
    name = "Unauthorized"
    msg = ""
class AccountNotWritable(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            131, ""
        )

    code = 131
    name = "AccountNotWritable"
    msg = ""
class AtaOwnerMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            132, ""
        )

    code = 132
    name = "AtaOwnerMismatch"
    msg = ""
class DelegationVersionMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            133, ""
        )

    code = 133
    name = "DelegationVersionMismatch"
    msg = ""
class MigrationRequired(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            134, ""
        )

    code = 134
    name = "MigrationRequired"
    msg = ""
class DelegationAlreadyExists(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            135, ""
        )

    code = 135
    name = "DelegationAlreadyExists"
    msg = ""
class StaleSubscriptionAuthority(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            136, ""
        )

    code = 136
    name = "StaleSubscriptionAuthority"
    msg = ""
class TransferHookTooManyAccounts(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            137, ""
        )

    code = 137
    name = "TransferHookTooManyAccounts"
    msg = ""
class AmountExceedsLimit(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            300, ""
        )

    code = 300
    name = "AmountExceedsLimit"
    msg = ""
class FixedDelegationExpiryInPast(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            301, ""
        )

    code = 301
    name = "FixedDelegationExpiryInPast"
    msg = ""
class FixedDelegationAmountZero(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            302, ""
        )

    code = 302
    name = "FixedDelegationAmountZero"
    msg = ""
class AmountExceedsPeriodLimit(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            400, ""
        )

    code = 400
    name = "AmountExceedsPeriodLimit"
    msg = ""
class PeriodNotElapsed(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            401, ""
        )

    code = 401
    name = "PeriodNotElapsed"
    msg = ""
class InvalidPeriodLength(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            402, ""
        )

    code = 402
    name = "InvalidPeriodLength"
    msg = ""
class InvalidPayerData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            403, ""
        )

    code = 403
    name = "InvalidPayerData"
    msg = ""
class RecurringDelegationStartTimeInPast(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            404, ""
        )

    code = 404
    name = "RecurringDelegationStartTimeInPast"
    msg = ""
class RecurringDelegationStartTimeGreaterThanExpiry(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            405, ""
        )

    code = 405
    name = "RecurringDelegationStartTimeGreaterThanExpiry"
    msg = ""
class RecurringDelegationAmountZero(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            406, ""
        )

    code = 406
    name = "RecurringDelegationAmountZero"
    msg = ""
class DelegationNotStarted(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            407, ""
        )

    code = 407
    name = "DelegationNotStarted"
    msg = ""
class RecurringDelegationStartOnLandingRequiresExpiry(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            408, ""
        )

    code = 408
    name = "RecurringDelegationStartOnLandingRequiresExpiry"
    msg = ""
class PlanSunset(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            500, ""
        )

    code = 500
    name = "PlanSunset"
    msg = ""
class PlanExpired(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            501, ""
        )

    code = 501
    name = "PlanExpired"
    msg = ""
class InvalidPlanPda(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            502, ""
        )

    code = 502
    name = "InvalidPlanPda"
    msg = ""
class InvalidSubscriptionPda(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            503, ""
        )

    code = 503
    name = "InvalidSubscriptionPda"
    msg = ""
class NotPlanOwner(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            504, ""
        )

    code = 504
    name = "NotPlanOwner"
    msg = ""
class SubscriptionPlanMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            505, ""
        )

    code = 505
    name = "SubscriptionPlanMismatch"
    msg = ""
class UnauthorizedDestination(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            506, ""
        )

    code = 506
    name = "UnauthorizedDestination"
    msg = ""
class InvalidNumDestinations(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            507, ""
        )

    code = 507
    name = "InvalidNumDestinations"
    msg = ""
class SubscriptionCancelled(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            508, ""
        )

    code = 508
    name = "SubscriptionCancelled"
    msg = ""
class SubscriptionAlreadyCancelled(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            509, ""
        )

    code = 509
    name = "SubscriptionAlreadyCancelled"
    msg = ""
class SubscriptionNotCancelled(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            510, ""
        )

    code = 510
    name = "SubscriptionNotCancelled"
    msg = ""
class InvalidEndTs(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            511, ""
        )

    code = 511
    name = "InvalidEndTs"
    msg = ""
class InvalidPlanStatus(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            512, ""
        )

    code = 512
    name = "InvalidPlanStatus"
    msg = ""
class PlanImmutableAfterSunset(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            513, ""
        )

    code = 513
    name = "PlanImmutableAfterSunset"
    msg = ""
class SunsetRequiresEndTs(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            514, ""
        )

    code = 514
    name = "SunsetRequiresEndTs"
    msg = ""
class PlanNotExpired(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            515, ""
        )

    code = 515
    name = "PlanNotExpired"
    msg = ""
class PlanClosed(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            516, ""
        )

    code = 516
    name = "PlanClosed"
    msg = ""
class AlreadySubscribed(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            517, ""
        )

    code = 517
    name = "AlreadySubscribed"
    msg = ""
class PlanAlreadyExists(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            518, ""
        )

    code = 518
    name = "PlanAlreadyExists"
    msg = ""
class PlanTermsMismatch(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            519, ""
        )

    code = 519
    name = "PlanTermsMismatch"
    msg = ""
class PlanEndTsCannotExtend(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            520, ""
        )

    code = 520
    name = "PlanEndTsCannotExtend"
    msg = ""
class StaleSubscriptionApproval(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            521, ""
        )

    code = 521
    name = "StaleSubscriptionApproval"
    msg = ""
class StalePlanApproval(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            522, ""
        )

    code = 522
    name = "StalePlanApproval"
    msg = ""
class InvalidEventAuthority(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            600, ""
        )

    code = 600
    name = "InvalidEventAuthority"
    msg = ""
class InvalidEventData(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            601, ""
        )

    code = 601
    name = "InvalidEventData"
    msg = ""
class InvalidEventTag(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            602, ""
        )

    code = 602
    name = "InvalidEventTag"
    msg = ""
class InvalidEventDiscriminator(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            603, ""
        )

    code = 603
    name = "InvalidEventDiscriminator"
    msg = ""
class InvalidSelfProgram(ProgramError):
    def __init__(self) -> None:
        super().__init__(
            604, ""
        )

    code = 604
    name = "InvalidSelfProgram"
    msg = ""

CustomError = typing.Union[
    NotSigner,
    InvalidAddress,
    InvalidEscrowPda,
    InvalidSubscriptionAuthorityPda,
    NotSystemProgram,
    InvalidTokenProgram,
    InvalidToken2022MintAccountData,
    InvalidToken2022TokenAccountData,
    InvalidAssociatedTokenAccountDerivedAddress,
    InvalidTokenSplMintAccountData,
    InvalidTokenSplTokenAccountData,
    InvalidAccountData,
    InvalidInstructionData,
    NotEnoughAccountKeys,
    InvalidInstruction,
    ArithmeticOverflow,
    ArithmeticUnderflow,
    InvalidAccountDiscriminator,
    MintHasConfidentialTransfer,
    MintHasNonTransferable,
    MintHasPermanentDelegate,
    MintHasTransferHook,
    MintHasTransferFee,
    MintHasMintCloseAuthority,
    MintHasPausable,
    MintMismatch,
    InvalidDelegatePda,
    InvalidHeaderData,
    DelegationExpired,
    InvalidAmount,
    Unauthorized,
    AccountNotWritable,
    AtaOwnerMismatch,
    DelegationVersionMismatch,
    MigrationRequired,
    DelegationAlreadyExists,
    StaleSubscriptionAuthority,
    TransferHookTooManyAccounts,
    AmountExceedsLimit,
    FixedDelegationExpiryInPast,
    FixedDelegationAmountZero,
    AmountExceedsPeriodLimit,
    PeriodNotElapsed,
    InvalidPeriodLength,
    InvalidPayerData,
    RecurringDelegationStartTimeInPast,
    RecurringDelegationStartTimeGreaterThanExpiry,
    RecurringDelegationAmountZero,
    DelegationNotStarted,
    RecurringDelegationStartOnLandingRequiresExpiry,
    PlanSunset,
    PlanExpired,
    InvalidPlanPda,
    InvalidSubscriptionPda,
    NotPlanOwner,
    SubscriptionPlanMismatch,
    UnauthorizedDestination,
    InvalidNumDestinations,
    SubscriptionCancelled,
    SubscriptionAlreadyCancelled,
    SubscriptionNotCancelled,
    InvalidEndTs,
    InvalidPlanStatus,
    PlanImmutableAfterSunset,
    SunsetRequiresEndTs,
    PlanNotExpired,
    PlanClosed,
    AlreadySubscribed,
    PlanAlreadyExists,
    PlanTermsMismatch,
    PlanEndTsCannotExtend,
    StaleSubscriptionApproval,
    StalePlanApproval,
    InvalidEventAuthority,
    InvalidEventData,
    InvalidEventTag,
    InvalidEventDiscriminator,
    InvalidSelfProgram,
 ]
CUSTOM_ERROR_MAP: dict[int, CustomError] = {
    100: NotSigner(),
    101: InvalidAddress(),
    102: InvalidEscrowPda(),
    103: InvalidSubscriptionAuthorityPda(),
    104: NotSystemProgram(),
    105: InvalidTokenProgram(),
    106: InvalidToken2022MintAccountData(),
    107: InvalidToken2022TokenAccountData(),
    108: InvalidAssociatedTokenAccountDerivedAddress(),
    109: InvalidTokenSplMintAccountData(),
    110: InvalidTokenSplTokenAccountData(),
    111: InvalidAccountData(),
    112: InvalidInstructionData(),
    113: NotEnoughAccountKeys(),
    114: InvalidInstruction(),
    115: ArithmeticOverflow(),
    116: ArithmeticUnderflow(),
    117: InvalidAccountDiscriminator(),
    118: MintHasConfidentialTransfer(),
    119: MintHasNonTransferable(),
    120: MintHasPermanentDelegate(),
    121: MintHasTransferHook(),
    122: MintHasTransferFee(),
    123: MintHasMintCloseAuthority(),
    124: MintHasPausable(),
    125: MintMismatch(),
    126: InvalidDelegatePda(),
    127: InvalidHeaderData(),
    128: DelegationExpired(),
    129: InvalidAmount(),
    130: Unauthorized(),
    131: AccountNotWritable(),
    132: AtaOwnerMismatch(),
    133: DelegationVersionMismatch(),
    134: MigrationRequired(),
    135: DelegationAlreadyExists(),
    136: StaleSubscriptionAuthority(),
    137: TransferHookTooManyAccounts(),
    300: AmountExceedsLimit(),
    301: FixedDelegationExpiryInPast(),
    302: FixedDelegationAmountZero(),
    400: AmountExceedsPeriodLimit(),
    401: PeriodNotElapsed(),
    402: InvalidPeriodLength(),
    403: InvalidPayerData(),
    404: RecurringDelegationStartTimeInPast(),
    405: RecurringDelegationStartTimeGreaterThanExpiry(),
    406: RecurringDelegationAmountZero(),
    407: DelegationNotStarted(),
    408: RecurringDelegationStartOnLandingRequiresExpiry(),
    500: PlanSunset(),
    501: PlanExpired(),
    502: InvalidPlanPda(),
    503: InvalidSubscriptionPda(),
    504: NotPlanOwner(),
    505: SubscriptionPlanMismatch(),
    506: UnauthorizedDestination(),
    507: InvalidNumDestinations(),
    508: SubscriptionCancelled(),
    509: SubscriptionAlreadyCancelled(),
    510: SubscriptionNotCancelled(),
    511: InvalidEndTs(),
    512: InvalidPlanStatus(),
    513: PlanImmutableAfterSunset(),
    514: SunsetRequiresEndTs(),
    515: PlanNotExpired(),
    516: PlanClosed(),
    517: AlreadySubscribed(),
    518: PlanAlreadyExists(),
    519: PlanTermsMismatch(),
    520: PlanEndTsCannotExtend(),
    521: StaleSubscriptionApproval(),
    522: StalePlanApproval(),
    600: InvalidEventAuthority(),
    601: InvalidEventData(),
    602: InvalidEventTag(),
    603: InvalidEventDiscriminator(),
    604: InvalidSelfProgram(),
}

def from_code(code: int) -> typing.Optional[CustomError]:
    maybe_err = CUSTOM_ERROR_MAP.get(code)
    if maybe_err is None:
        return None
    return maybe_err

