package com.solana.mpp.crypto

import com.solana.mpp.protocol.*

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

class PdaTest {
    /**
     * Parity oracle: the Associated Token Account for owner
     * `7gWmoAuwc5jR59ZF8aBpVTLeeMtJBg7Tr3iDaXFwfDgB` holding mint
     * `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v` (Solana USDC) under
     * the SPL Token program is
     * `2xyhP3ZCpBqnjPe1oLzQCXqb5kMrJHY6sVkt7x4mBUz5` (bump 253).
     *
     * Generated by running `Pubkey::find_program_address` directly from
     * the Solana SDK (the same primitive the Rust spine uses at
     * rust/src/client/charge.rs::get_associated_token_address, line 468);
     * see rust/examples/check_ata.rs for the standalone reproducer.
     */
    @Test
    fun associatedTokenAddressMatchesSolanaSdk() {
        val owner = PublicKey.fromBase58("7gWmoAuwc5jR59ZF8aBpVTLeeMtJBg7Tr3iDaXFwfDgB")
        val mint = PublicKey.fromBase58("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v")
        val tokenProgram = PublicKey.fromBase58(Programs.TOKEN_PROGRAM)
        val ata = Pda.associatedTokenAddress(owner, mint, tokenProgram)

        assertEquals("2xyhP3ZCpBqnjPe1oLzQCXqb5kMrJHY6sVkt7x4mBUz5", ata.toBase58())
    }

    @Test
    fun associatedTokenAddressDiffersBetweenTokenAndToken2022() {
        val owner = PublicKey.fromBase58("7gWmoAuwc5jR59ZF8aBpVTLeeMtJBg7Tr3iDaXFwfDgB")
        val mint = PublicKey.fromBase58("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v")
        val token = PublicKey.fromBase58(Programs.TOKEN_PROGRAM)
        val token2022 = PublicKey.fromBase58(Programs.TOKEN_2022_PROGRAM)

        assertNotEquals(
            Pda.associatedTokenAddress(owner, mint, token).toBase58(),
            Pda.associatedTokenAddress(owner, mint, token2022).toBase58(),
        )
    }

    @Test
    fun findProgramAddressIsDeterministic() {
        val programId = PublicKey.fromBase58(Programs.ASSOCIATED_TOKEN_PROGRAM)
        val seed = "test-seed".encodeToByteArray()
        val (first, bumpA) = Pda.findProgramAddress(listOf(seed), programId)
        val (second, bumpB) = Pda.findProgramAddress(listOf(seed), programId)
        assertEquals(first, second)
        assertEquals(bumpA, bumpB)
        assertTrue(bumpA in 0..255)
    }

    @Test
    fun publicKeyRoundTripsBase58() {
        val bytes = ByteArray(32) { (it * 11 xor 0x37).toByte() }
        val key = PublicKey(bytes)
        assertEquals(key, PublicKey.fromBase58(key.toBase58()))
    }

    @Test
    fun publicKeyRejectsWrongLength() {
        assertFailsWith<IllegalArgumentException> { PublicKey(ByteArray(31)) }
        assertFailsWith<MppException.InvalidPublicKey> {
            PublicKey.fromBase58("11111111111111111111111111111111111111111111")
        }
        assertFailsWith<MppException.InvalidPublicKey> { PublicKey.fromBase58("not-base58!") }
    }

    @Test
    fun publicKeyEqualsAndHashAreContentBased() {
        val a = PublicKey(ByteArray(32) { it.toByte() })
        val b = PublicKey(ByteArray(32) { it.toByte() })
        assertEquals(a, b)
        assertEquals(a.hashCode(), b.hashCode())
    }
}
