'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS


class FixedDelegationJSON(typing.TypedDict):
    header: types.header.HeaderJSON
    subscriptionAuthority: str
    mint: str
    amount: int
    expiryTs: int

@dataclass
class FixedDelegation:
    #fields
    header: types.header.Header
    subscriptionAuthority: SolPubkey
    mint: SolPubkey
    amount: int
    expiryTs: int



    layout: typing.ClassVar = borsh.CStruct(
        "header" /types.header.Header.layout,
        "subscriptionAuthority" /BorshPubkey,
        "mint" /BorshPubkey,
        "amount" /borsh.U64,
        "expiryTs" /borsh.I64,
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.Optional["FixedDelegation"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.List[typing.Optional["FixedDelegation"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["FixedDelegation"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "FixedDelegation":
        dec = FixedDelegation.layout.parse(data[1:])
        return cls(
                header=types.header.Header.from_decoded(dec.header),
                subscriptionAuthority=dec.subscriptionAuthority,
                mint=dec.mint,
                amount=dec.amount,
                expiryTs=dec.expiryTs,
                )
    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "header": self.header.to_encodable(),
                "subscriptionAuthority": self.subscriptionAuthority,
                "mint": self.mint,
                "amount": self.amount,
                "expiryTs": self.expiryTs,
                }
    def to_json(self) -> FixedDelegationJSON:
        return {
                "header": self.header.to_json(),
                "subscriptionAuthority": str(self.subscriptionAuthority),
                "mint": str(self.mint),
                "amount": self.amount,
                "expiryTs": self.expiryTs,
                }

    @classmethod
    def from_json(cls, obj: FixedDelegationJSON) -> "FixedDelegation":
        return cls(
                header=types.header.Header.from_json(obj["header"]),
                subscriptionAuthority=SolPubkey.from_string(obj["subscriptionAuthority"]),
                mint=SolPubkey.from_string(obj["mint"]),
                amount=obj["amount"],
                expiryTs=obj["expiryTs"],
                )




