'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS


class PlanJSON(typing.TypedDict):
    owner: str
    bump: int
    status: int
    data: types.planData.PlanDataJSON

@dataclass
class Plan:
    #fields
    owner: SolPubkey
    bump: int
    status: int
    data: types.planData.PlanData



    layout: typing.ClassVar = borsh.CStruct(
        "owner" /BorshPubkey,
        "bump" /borsh.U8,
        "status" /borsh.U8,
        "data" /types.planData.PlanData.layout,
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.Optional["Plan"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.List[typing.Optional["Plan"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["Plan"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "Plan":
        dec = Plan.layout.parse(data[1:])
        return cls(
                owner=dec.owner,
                bump=dec.bump,
                status=dec.status,
                data=types.planData.PlanData.from_decoded(dec.data),
                )
    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "owner": self.owner,
                "bump": self.bump,
                "status": self.status,
                "data": self.data.to_encodable(),
                }
    def to_json(self) -> PlanJSON:
        return {
                "owner": str(self.owner),
                "bump": self.bump,
                "status": self.status,
                "data": self.data.to_json(),
                }

    @classmethod
    def from_json(cls, obj: PlanJSON) -> "Plan":
        return cls(
                owner=SolPubkey.from_string(obj["owner"]),
                bump=obj["bump"],
                status=obj["status"],
                data=types.planData.PlanData.from_json(obj["data"]),
                )




