'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS


class RecurringDelegationJSON(typing.TypedDict):
    header: types.header.HeaderJSON
    subscriptionAuthority: str
    mint: str
    currentPeriodStartTs: int
    periodLengthS: int
    expiryTs: int
    amountPerPeriod: int
    amountPulledInPeriod: int

@dataclass
class RecurringDelegation:
    #fields
    header: types.header.Header
    subscriptionAuthority: SolPubkey
    mint: SolPubkey
    currentPeriodStartTs: int
    periodLengthS: int
    expiryTs: int
    amountPerPeriod: int
    amountPulledInPeriod: int



    layout: typing.ClassVar = borsh.CStruct(
        "header" /types.header.Header.layout,
        "subscriptionAuthority" /BorshPubkey,
        "mint" /BorshPubkey,
        "currentPeriodStartTs" /borsh.I64,
        "periodLengthS" /borsh.U64,
        "expiryTs" /borsh.I64,
        "amountPerPeriod" /borsh.U64,
        "amountPulledInPeriod" /borsh.U64,
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.Optional["RecurringDelegation"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.List[typing.Optional["RecurringDelegation"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["RecurringDelegation"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "RecurringDelegation":
        dec = RecurringDelegation.layout.parse(data[1:])
        return cls(
                header=types.header.Header.from_decoded(dec.header),
                subscriptionAuthority=dec.subscriptionAuthority,
                mint=dec.mint,
                currentPeriodStartTs=dec.currentPeriodStartTs,
                periodLengthS=dec.periodLengthS,
                expiryTs=dec.expiryTs,
                amountPerPeriod=dec.amountPerPeriod,
                amountPulledInPeriod=dec.amountPulledInPeriod,
                )
    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "header": self.header.to_encodable(),
                "subscriptionAuthority": self.subscriptionAuthority,
                "mint": self.mint,
                "currentPeriodStartTs": self.currentPeriodStartTs,
                "periodLengthS": self.periodLengthS,
                "expiryTs": self.expiryTs,
                "amountPerPeriod": self.amountPerPeriod,
                "amountPulledInPeriod": self.amountPulledInPeriod,
                }
    def to_json(self) -> RecurringDelegationJSON:
        return {
                "header": self.header.to_json(),
                "subscriptionAuthority": str(self.subscriptionAuthority),
                "mint": str(self.mint),
                "currentPeriodStartTs": self.currentPeriodStartTs,
                "periodLengthS": self.periodLengthS,
                "expiryTs": self.expiryTs,
                "amountPerPeriod": self.amountPerPeriod,
                "amountPulledInPeriod": self.amountPulledInPeriod,
                }

    @classmethod
    def from_json(cls, obj: RecurringDelegationJSON) -> "RecurringDelegation":
        return cls(
                header=types.header.Header.from_json(obj["header"]),
                subscriptionAuthority=SolPubkey.from_string(obj["subscriptionAuthority"]),
                mint=SolPubkey.from_string(obj["mint"]),
                currentPeriodStartTs=obj["currentPeriodStartTs"],
                periodLengthS=obj["periodLengthS"],
                expiryTs=obj["expiryTs"],
                amountPerPeriod=obj["amountPerPeriod"],
                amountPulledInPeriod=obj["amountPulledInPeriod"],
                )




