'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS


class SubscriptionDelegationJSON(typing.TypedDict):
    header: types.header.HeaderJSON
    terms: types.planTerms.PlanTermsJSON
    amountPulledInPeriod: int
    currentPeriodStartTs: int
    expiresAtTs: int

@dataclass
class SubscriptionDelegation:
    #fields
    header: types.header.Header
    terms: types.planTerms.PlanTerms
    amountPulledInPeriod: int
    currentPeriodStartTs: int
    expiresAtTs: int



    layout: typing.ClassVar = borsh.CStruct(
        "header" /types.header.Header.layout,
        "terms" /types.planTerms.PlanTerms.layout,
        "amountPulledInPeriod" /borsh.U64,
        "currentPeriodStartTs" /borsh.I64,
        "expiresAtTs" /borsh.I64,
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.Optional["SubscriptionDelegation"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.List[typing.Optional["SubscriptionDelegation"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["SubscriptionDelegation"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "SubscriptionDelegation":
        dec = SubscriptionDelegation.layout.parse(data[1:])
        return cls(
                header=types.header.Header.from_decoded(dec.header),
                terms=types.planTerms.PlanTerms.from_decoded(dec.terms),
                amountPulledInPeriod=dec.amountPulledInPeriod,
                currentPeriodStartTs=dec.currentPeriodStartTs,
                expiresAtTs=dec.expiresAtTs,
                )
    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "header": self.header.to_encodable(),
                "terms": self.terms.to_encodable(),
                "amountPulledInPeriod": self.amountPulledInPeriod,
                "currentPeriodStartTs": self.currentPeriodStartTs,
                "expiresAtTs": self.expiresAtTs,
                }
    def to_json(self) -> SubscriptionDelegationJSON:
        return {
                "header": self.header.to_json(),
                "terms": self.terms.to_json(),
                "amountPulledInPeriod": self.amountPulledInPeriod,
                "currentPeriodStartTs": self.currentPeriodStartTs,
                "expiresAtTs": self.expiresAtTs,
                }

    @classmethod
    def from_json(cls, obj: SubscriptionDelegationJSON) -> "SubscriptionDelegation":
        return cls(
                header=types.header.Header.from_json(obj["header"]),
                terms=types.planTerms.PlanTerms.from_json(obj["terms"]),
                amountPulledInPeriod=obj["amountPulledInPeriod"],
                currentPeriodStartTs=obj["currentPeriodStartTs"],
                expiresAtTs=obj["expiresAtTs"],
                )




