'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS


class SubscriptionAuthorityJSON(typing.TypedDict):
    user: str
    tokenMint: str
    payer: str
    bump: int
    initId: int

@dataclass
class SubscriptionAuthority:
    #fields
    user: SolPubkey
    tokenMint: SolPubkey
    payer: SolPubkey
    bump: int
    initId: int



    layout: typing.ClassVar = borsh.CStruct(
        "user" /BorshPubkey,
        "tokenMint" /BorshPubkey,
        "payer" /BorshPubkey,
        "bump" /borsh.U8,
        "initId" /borsh.I64,
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.Optional["SubscriptionAuthority"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = SUBSCRIPTIONS_PROGRAM_ADDRESS,
    ) -> typing.List[typing.Optional["SubscriptionAuthority"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["SubscriptionAuthority"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "SubscriptionAuthority":
        dec = SubscriptionAuthority.layout.parse(data[1:])
        return cls(
                user=dec.user,
                tokenMint=dec.tokenMint,
                payer=dec.payer,
                bump=dec.bump,
                initId=dec.initId,
                )
    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "user": self.user,
                "tokenMint": self.tokenMint,
                "payer": self.payer,
                "bump": self.bump,
                "initId": self.initId,
                }
    def to_json(self) -> SubscriptionAuthorityJSON:
        return {
                "user": str(self.user),
                "tokenMint": str(self.tokenMint),
                "payer": str(self.payer),
                "bump": self.bump,
                "initId": self.initId,
                }

    @classmethod
    def from_json(cls, obj: SubscriptionAuthorityJSON) -> "SubscriptionAuthority":
        return cls(
                user=SolPubkey.from_string(obj["user"]),
                tokenMint=SolPubkey.from_string(obj["tokenMint"]),
                payer=SolPubkey.from_string(obj["payer"]),
                bump=obj["bump"],
                initId=obj["initId"],
                )




