// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

import (
	ag_binary "github.com/gagliardetto/binary"
)

type ClosedChannel struct {
	Discriminator uint8
}

func (obj *ClosedChannel) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	{
		err := encoder.Encode(obj.Discriminator)
		if err != nil {
			return err
		}
	}
	return nil
}

func (obj *ClosedChannel) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	{
		err := decoder.Decode(&obj.Discriminator)
		if err != nil {
			return err
		}
	}
	return nil
}
