// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

import (
	"fmt"

	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

var SettleAndFinalizeDiscriminator = 4

// SettleAndFinalize is the `SettleAndFinalize` instruction.
type SettleAndFinalize struct {
	// [0] = [SIGNER] Merchant
	// [1] = [WRITE] Channel
	// [2] = [] InstructionsSysvar
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
	// SettleAndFinalizeArgs holds the Borsh-encoded instruction arguments
	// written after the settleAndFinalize discriminator byte (4): the
	// optional final voucher plus the hasVoucher flag selecting whether the
	// Ed25519 precompile check applies.
	SettleAndFinalizeArgs SettleAndFinalizeArgs
}

// NewSettleAndFinalizeInstructionBuilder creates a new `SettleAndFinalize` instruction builder.
func NewSettleAndFinalizeInstructionBuilder() *SettleAndFinalize {
	nd := &SettleAndFinalize{}
	nd.AccountMetaSlice = make(ag_solanago.AccountMetaSlice, 3)
	return nd
}

// SetSettleAndFinalizeArgs sets the "settle_and_finalize_args" parameter.
func (inst *SettleAndFinalize) SetSettleAndFinalizeArgs(settleAndFinalizeArgs SettleAndFinalizeArgs) *SettleAndFinalize {
	inst.SettleAndFinalizeArgs = settleAndFinalizeArgs
	return inst
}

// SetMerchantAccount sets the "merchant" account.
func (inst *SettleAndFinalize) SetMerchantAccount(merchant ag_solanago.PublicKey) *SettleAndFinalize {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(merchant).SIGNER()
	return inst
}

// GetMerchantAccount gets the "merchant" account.
func (inst *SettleAndFinalize) GetMerchantAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetChannelAccount sets the "channel" account.
func (inst *SettleAndFinalize) SetChannelAccount(channel ag_solanago.PublicKey) *SettleAndFinalize {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(channel).WRITE()
	return inst
}

// GetChannelAccount gets the "channel" account.
func (inst *SettleAndFinalize) GetChannelAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetInstructionsSysvarAccount sets the "instructions_sysvar" account.
func (inst *SettleAndFinalize) SetInstructionsSysvarAccount(instructionsSysvar ag_solanago.PublicKey) *SettleAndFinalize {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(instructionsSysvar)
	return inst
}

// GetInstructionsSysvarAccount gets the "instructions_sysvar" account.
func (inst *SettleAndFinalize) GetInstructionsSysvarAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

func (inst SettleAndFinalize) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: ag_binary.NoTypeIDDefaultID,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SettleAndFinalize) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SettleAndFinalize) Validate() error {
	if inst.AccountMetaSlice[0] == nil {
		return fmt.Errorf("accounts.Merchant is not set")
	}
	if inst.AccountMetaSlice[1] == nil {
		return fmt.Errorf("accounts.Channel is not set")
	}
	if inst.AccountMetaSlice[2] == nil {
		return fmt.Errorf("accounts.InstructionsSysvar is not set")
	}
	return nil
}

func (inst *SettleAndFinalize) GetAccounts() (out []*ag_solanago.AccountMeta) {
	return inst.AccountMetaSlice
}

func (inst *SettleAndFinalize) SetAccounts(accounts []*ag_solanago.AccountMeta) error {
	if len(accounts) < 3 {
		return fmt.Errorf("not enough accounts: expected at least 3, got %d", len(accounts))
	}
	inst.AccountMetaSlice = accounts[:3]
	return nil
}

func (inst *SettleAndFinalize) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	{
		err := encoder.Encode(uint8(4))
		if err != nil {
			return err
		}
	}
	{
		err := encoder.Encode(inst.SettleAndFinalizeArgs)
		if err != nil {
			return err
		}
	}
	return nil
}

func (inst *SettleAndFinalize) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	{
		var tmp uint8
		err := decoder.Decode(&tmp)
		if err != nil {
			return err
		}
	}
	{
		err := decoder.Decode(&inst.SettleAndFinalizeArgs)
		if err != nil {
			return err
		}
	}
	return nil
}
