// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

import (
	"bytes"
	"fmt"

	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

const ProgramName = "PaymentChannels"

var ProgramID ag_solanago.PublicKey = ag_solanago.MustPublicKeyFromBase58("CHNLxYvVA28MJP9PrFuDXccuoGXAx7jBacfLEkahyGsX")

func SetProgramID(pubkey ag_solanago.PublicKey) {
	ProgramID = pubkey
	ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

var (
	Instruction_9_Count uint32 = 9

	InstructionImplDef = ag_binary.NewVariantDefinition(
		ag_binary.Uint8TypeIDEncoding,
		[]ag_binary.VariantType{
			{
				"Distribute",
				(*Distribute)(nil),
			},
			{
				"EmitEvent",
				(*EmitEvent)(nil),
			},
			{
				"Finalize",
				(*Finalize)(nil),
			},
			{
				"Open",
				(*Open)(nil),
			},
			{
				"RequestClose",
				(*RequestClose)(nil),
			},
			{
				"Settle",
				(*Settle)(nil),
			},
			{
				"SettleAndFinalize",
				(*SettleAndFinalize)(nil),
			},
			{
				"TopUp",
				(*TopUp)(nil),
			},
			{
				"WithdrawPayer",
				(*WithdrawPayer)(nil),
			},
		},
	)
)

type Instruction struct {
	ag_binary.BaseVariant
}

func (inst *Instruction) ProgramID() ag_solanago.PublicKey {
	return ProgramID
}

func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {
	return inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()
}

func (inst *Instruction) Data() ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {
		return nil, fmt.Errorf("unable to encode instruction: %w", err)
	}
	return buf.Bytes(), nil
}

func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	return inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)
}

func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	err := encoder.WriteUint8(inst.TypeID.Uint8())
	if err != nil {
		return fmt.Errorf("unable to write variant type: %w", err)
	}
	return encoder.Encode(inst.Impl)
}

func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {
	inst, err := DecodeInstruction(accounts, data)
	if err != nil {
		return nil, err
	}
	return inst, nil
}

func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {
	inst := new(Instruction)
	if err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {
		return nil, fmt.Errorf("unable to decode instruction: %w", err)
	}
	if v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {
		err := v.SetAccounts(accounts)
		if err != nil {
			return nil, fmt.Errorf("unable to set accounts for instruction: %w", err)
		}
	}
	return inst, nil
}
