// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

import (
	"fmt"

	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

var FinalizeDiscriminator = 6

// Finalize is the `Finalize` instruction.
type Finalize struct {
	// [0] = [WRITE] Channel
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewFinalizeInstructionBuilder creates a new `Finalize` instruction builder.
func NewFinalizeInstructionBuilder() *Finalize {
	nd := &Finalize{}
	nd.AccountMetaSlice = make(ag_solanago.AccountMetaSlice, 1)
	return nd
}

// SetChannelAccount sets the "channel" account.
func (inst *Finalize) SetChannelAccount(channel ag_solanago.PublicKey) *Finalize {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(channel).WRITE()
	return inst
}

// GetChannelAccount gets the "channel" account.
func (inst *Finalize) GetChannelAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

func (inst Finalize) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: ag_binary.NoTypeIDDefaultID,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Finalize) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Finalize) Validate() error {
	if inst.AccountMetaSlice[0] == nil {
		return fmt.Errorf("accounts.Channel is not set")
	}
	return nil
}

func (inst *Finalize) GetAccounts() (out []*ag_solanago.AccountMeta) {
	return inst.AccountMetaSlice
}

func (inst *Finalize) SetAccounts(accounts []*ag_solanago.AccountMeta) error {
	if len(accounts) < 1 {
		return fmt.Errorf("not enough accounts: expected at least 1, got %d", len(accounts))
	}
	inst.AccountMetaSlice = accounts[:1]
	return nil
}

func (inst *Finalize) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	{
		err := encoder.Encode(uint8(6))
		if err != nil {
			return err
		}
	}
	return nil
}

func (inst *Finalize) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	{
		var tmp uint8
		err := decoder.Decode(&tmp)
		if err != nil {
			return err
		}
	}
	return nil
}
