// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

type SettleAndFinalizeArgs struct {
	// Voucher is the final voucher committed before the channel is
	// finalized; its contents are only meaningful when HasVoucher is 1.
	Voucher VoucherArgs
	// HasVoucher is a Borsh bool flag: 1 settles Voucher (verified through
	// a preceding Ed25519 precompile instruction referenced via the
	// instructions sysvar) before finalizing, 0 finalizes without one.
	HasVoucher uint8
}
