// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

import (
	ag_solanago "github.com/gagliardetto/solana-go"
)

type Opened struct {
	// Channel is the PDA of the channel account created by the open
	// instruction, derived from ["channel", payer, payee, mint,
	// authorizedSigner, salt as little-endian u64].
	Channel ag_solanago.PublicKey
}
