// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

type TopUpArgs struct {
	// Amount is the additional deposit transferred from the payer into the
	// channel token account, in mint base units; a delta added to the
	// channel's deposit total, not a cumulative figure.
	Amount uint64
}
