// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

type SettlementWatermarks struct {
	// Settled is the cumulative amount committed by settled vouchers over
	// the channel lifetime, in mint base units; it only ever increases.
	Settled uint64
	// PayoutWatermark is the cumulative amount already paid out to
	// recipients over the channel lifetime, in mint base units; the unpaid
	// remainder is Settled minus PayoutWatermark.
	PayoutWatermark uint64
}
