// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

import (
	ag_solanago "github.com/gagliardetto/solana-go"
)

type DistributionEntry struct {
	// Recipient is the raw 32-byte public key of the split recipient
	// wallet; its associated token account for the channel mint receives
	// this entry's share at distribution.
	Recipient ag_solanago.PublicKey
	// Bps is the recipient's share of the settled amount in basis points
	// (1 bps = 0.01%).
	Bps uint16
}
