// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

import (
	ag_solanago "github.com/gagliardetto/solana-go"
)

type DistributionEntry struct {
	Recipient ag_solanago.PublicKey
	Bps       uint16
}
