// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

type DistributeArgs struct {
	// Recipients is the basis-point split list paid out at distribution,
	// Borsh-encoded with a little-endian u32 length prefix; it must hash to
	// the distribution hash committed in the channel account at open.
	Recipients []DistributionEntry
}
