// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

type ChannelStatus uint8

const (
	ChannelStatus_Open ChannelStatus = iota
	ChannelStatus_Finalized
	ChannelStatus_Closing
)
