// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

type RedirectReason uint8

const (
	RedirectReason_UnsupportedExtension RedirectReason = iota
	RedirectReason_ClosedOrMalformed
	RedirectReason_NotInitialized
	RedirectReason_ReassignedAuthority
)
