// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

type OpenArgs struct {
	Salt        uint64
	Deposit     uint64
	GracePeriod uint32
	OpenSlot    uint64
	Recipients  []DistributionEntry
}
