// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package payment_channels

import (
	ag_solanago "github.com/gagliardetto/solana-go"
)

type VoucherArgs struct {
	// ChannelId is the raw 32-byte channel PDA the voucher settles against;
	// it forms bytes 0..32 of the 48-byte Ed25519 signing preimage.
	ChannelId ag_solanago.PublicKey
	// CumulativeAmount is the total authorized over the channel lifetime in
	// mint base units (a running total, not a per-voucher delta), encoded
	// as a little-endian u64 at bytes 32..40 of the signing preimage.
	CumulativeAmount uint64
	// ExpiresAt is the voucher expiry as a Unix timestamp in seconds,
	// encoded as a little-endian i64 at bytes 40..48 of the signing
	// preimage.
	ExpiresAt int64
}
