'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class ChannelJSON(typing.TypedDict):
    kind: typing.Literal["Channel"]


@dataclass
class Channel:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> ChannelJSON:
        return ChannelJSON(
            kind="Channel",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Channel": {},
        }




class ClosedChannelJSON(typing.TypedDict):
    kind: typing.Literal["ClosedChannel"]


@dataclass
class ClosedChannel:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> ClosedChannelJSON:
        return ClosedChannelJSON(
            kind="ClosedChannel",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "ClosedChannel": {},
        }





AccountDiscriminatorKind = typing.Union[
    Channel,
    ClosedChannel,
]
AccountDiscriminatorJSON = typing.Union[
    ChannelJSON,
    ClosedChannelJSON,
]

def from_decoded(obj: dict) -> AccountDiscriminatorKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "Channel" in obj:
      return Channel()
    if "ClosedChannel" in obj:
      return ClosedChannel()
    raise ValueError("Invalid enum object")

def from_json(obj: AccountDiscriminatorJSON) -> AccountDiscriminatorKind:
    if obj["kind"] == "Channel":
        return Channel()

    if obj["kind"] == "ClosedChannel":
        return ClosedChannel()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"Channel" / borsh.CStruct(),
"ClosedChannel" / borsh.CStruct(),
)
