'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class OpenJSON(typing.TypedDict):
    kind: typing.Literal["Open"]


@dataclass
class Open:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> OpenJSON:
        return OpenJSON(
            kind="Open",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Open": {},
        }




class SealedJSON(typing.TypedDict):
    kind: typing.Literal["Sealed"]


@dataclass
class Sealed:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> SealedJSON:
        return SealedJSON(
            kind="Sealed",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Sealed": {},
        }




class ClosingJSON(typing.TypedDict):
    kind: typing.Literal["Closing"]


@dataclass
class Closing:
    discriminator: typing.ClassVar = 2
    def to_json(self) -> ClosingJSON:
        return ClosingJSON(
            kind="Closing",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Closing": {},
        }




class DistributedJSON(typing.TypedDict):
    kind: typing.Literal["Distributed"]


@dataclass
class Distributed:
    discriminator: typing.ClassVar = 3
    def to_json(self) -> DistributedJSON:
        return DistributedJSON(
            kind="Distributed",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Distributed": {},
        }





ChannelStatusKind = typing.Union[
    Open,
    Sealed,
    Closing,
    Distributed,
]
ChannelStatusJSON = typing.Union[
    OpenJSON,
    SealedJSON,
    ClosingJSON,
    DistributedJSON,
]

def from_decoded(obj: dict) -> ChannelStatusKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "Open" in obj:
      return Open()
    if "Sealed" in obj:
      return Sealed()
    if "Closing" in obj:
      return Closing()
    if "Distributed" in obj:
      return Distributed()
    raise ValueError("Invalid enum object")

def from_json(obj: ChannelStatusJSON) -> ChannelStatusKind:
    if obj["kind"] == "Open":
        return Open()

    if obj["kind"] == "Sealed":
        return Sealed()

    if obj["kind"] == "Closing":
        return Closing()

    if obj["kind"] == "Distributed":
        return Distributed()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"Open" / borsh.CStruct(),
"Sealed" / borsh.CStruct(),
"Closing" / borsh.CStruct(),
"Distributed" / borsh.CStruct(),
)
