'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class OpenJSON(typing.TypedDict):
    kind: typing.Literal["Open"]


@dataclass
class Open:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> OpenJSON:
        return OpenJSON(
            kind="Open",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Open": {},
        }




class FinalizedJSON(typing.TypedDict):
    kind: typing.Literal["Finalized"]


@dataclass
class Finalized:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> FinalizedJSON:
        return FinalizedJSON(
            kind="Finalized",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Finalized": {},
        }




class ClosingJSON(typing.TypedDict):
    kind: typing.Literal["Closing"]


@dataclass
class Closing:
    discriminator: typing.ClassVar = 2
    def to_json(self) -> ClosingJSON:
        return ClosingJSON(
            kind="Closing",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Closing": {},
        }





ChannelStatusKind = typing.Union[
    Open,
    Finalized,
    Closing,
]
ChannelStatusJSON = typing.Union[
    OpenJSON,
    FinalizedJSON,
    ClosingJSON,
]

def from_decoded(obj: dict) -> ChannelStatusKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "Open" in obj:
      return Open()
    if "Finalized" in obj:
      return Finalized()
    if "Closing" in obj:
      return Closing()
    raise ValueError("Invalid enum object")

def from_json(obj: ChannelStatusJSON) -> ChannelStatusKind:
    if obj["kind"] == "Open":
        return Open()

    if obj["kind"] == "Finalized":
        return Finalized()

    if obj["kind"] == "Closing":
        return Closing()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"Open" / borsh.CStruct(),
"Finalized" / borsh.CStruct(),
"Closing" / borsh.CStruct(),
)
