'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Construct, Container
from dataclasses import dataclass
from . import distributionEntry

class DistributeArgsJSON(typing.TypedDict):
    recipients: list[distributionEntry.DistributionEntryJSON]

@dataclass
class DistributeArgs:
    layout: typing.ClassVar = borsh.CStruct(
        "recipients" /borsh.Vec(typing.cast(Construct, distributionEntry.DistributionEntry.layout)),
        )
    #fields
    recipients: list[distributionEntry.DistributionEntry]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "DistributeArgs":
        return cls(
        recipients=list(map(lambda item:distributionEntry.DistributionEntry.from_decoded(item),obj["recipients"])),
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "recipients": list(map(lambda item:item.to_encodable(),self.recipients)),
                }

    def to_json(self) -> DistributeArgsJSON:
        return {
                "recipients": list(map(lambda item:item.to_json(),self.recipients)),
                }

    @classmethod
    def from_json(cls, obj: DistributeArgsJSON) -> "DistributeArgs":
        return cls(
                recipients=list(map(lambda item:distributionEntry.DistributionEntry.from_json(item),obj["recipients"])),
        )






