'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Construct, Container
from dataclasses import dataclass
from . import distributionEntry

class OpenArgsJSON(typing.TypedDict):
    salt: int
    deposit: int
    gracePeriod: int
    recipients: list[distributionEntry.DistributionEntryJSON]

@dataclass
class OpenArgs:
    layout: typing.ClassVar = borsh.CStruct(
        "salt" /borsh.U64,
        "deposit" /borsh.U64,
        "gracePeriod" /borsh.U32,
        "recipients" /borsh.Vec(typing.cast(Construct, distributionEntry.DistributionEntry.layout)),
        )
    #fields
    salt: int
    deposit: int
    gracePeriod: int
    recipients: list[distributionEntry.DistributionEntry]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "OpenArgs":
        return cls(
        salt=obj["salt"],
        deposit=obj["deposit"],
        gracePeriod=obj["gracePeriod"],
        recipients=list(map(lambda item:distributionEntry.DistributionEntry.from_decoded(item),obj["recipients"])),
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "salt": self.salt,
                "deposit": self.deposit,
                "gracePeriod": self.gracePeriod,
                "recipients": list(map(lambda item:item.to_encodable(),self.recipients)),
                }

    def to_json(self) -> OpenArgsJSON:
        return {
                "salt": self.salt,
                "deposit": self.deposit,
                "gracePeriod": self.gracePeriod,
                "recipients": list(map(lambda item:item.to_json(),self.recipients)),
                }

    @classmethod
    def from_json(cls, obj: OpenArgsJSON) -> "OpenArgs":
        return cls(
                salt=obj["salt"],
                deposit=obj["deposit"],
                gracePeriod=obj["gracePeriod"],
                recipients=list(map(lambda item:distributionEntry.DistributionEntry.from_json(item),obj["recipients"])),
        )






