'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class OpenedJSON(typing.TypedDict):
    channel: str
    openSlot: int

@dataclass
class Opened:
    layout: typing.ClassVar = borsh.CStruct(
        "channel" /BorshPubkey,
        "openSlot" /borsh.U64,
        )
    #fields
    channel: SolPubkey
    openSlot: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "Opened":
        return cls(
        channel=obj["channel"],
        openSlot=obj["openSlot"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "channel": self.channel,
                "openSlot": self.openSlot,
                }

    def to_json(self) -> OpenedJSON:
        return {
                "channel": str(self.channel),
                "openSlot": self.openSlot,
                }

    @classmethod
    def from_json(cls, obj: OpenedJSON) -> "Opened":
        return cls(
                channel=SolPubkey.from_string(obj["channel"]),
                openSlot=obj["openSlot"],
        )






