'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class RecipientJSON(typing.TypedDict):
    kind: typing.Literal["Recipient"]


@dataclass
class Recipient:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> RecipientJSON:
        return RecipientJSON(
            kind="Recipient",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Recipient": {},
        }




class PayeeJSON(typing.TypedDict):
    kind: typing.Literal["Payee"]


@dataclass
class Payee:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> PayeeJSON:
        return PayeeJSON(
            kind="Payee",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Payee": {},
        }




class PayerJSON(typing.TypedDict):
    kind: typing.Literal["Payer"]


@dataclass
class Payer:
    discriminator: typing.ClassVar = 2
    def to_json(self) -> PayerJSON:
        return PayerJSON(
            kind="Payer",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Payer": {},
        }





PayoutBeneficiaryKind = typing.Union[
    Recipient,
    Payee,
    Payer,
]
PayoutBeneficiaryJSON = typing.Union[
    RecipientJSON,
    PayeeJSON,
    PayerJSON,
]

def from_decoded(obj: dict) -> PayoutBeneficiaryKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "Recipient" in obj:
      return Recipient()
    if "Payee" in obj:
      return Payee()
    if "Payer" in obj:
      return Payer()
    raise ValueError("Invalid enum object")

def from_json(obj: PayoutBeneficiaryJSON) -> PayoutBeneficiaryKind:
    if obj["kind"] == "Recipient":
        return Recipient()

    if obj["kind"] == "Payee":
        return Payee()

    if obj["kind"] == "Payer":
        return Payer()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"Recipient" / borsh.CStruct(),
"Payee" / borsh.CStruct(),
"Payer" / borsh.CStruct(),
)
