'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey
from . import payoutBeneficiary, redirectReason

class PayoutRedirectedJSON(typing.TypedDict):
    channel: str
    owner: str
    amount: int
    beneficiary: payoutBeneficiary.PayoutBeneficiaryJSON
    reason: redirectReason.RedirectReasonJSON

@dataclass
class PayoutRedirected:
    layout: typing.ClassVar = borsh.CStruct(
        "channel" /BorshPubkey,
        "owner" /BorshPubkey,
        "amount" /borsh.U64,
        "beneficiary" /payoutBeneficiary.layout,
        "reason" /redirectReason.layout,
        )
    #fields
    channel: SolPubkey
    owner: SolPubkey
    amount: int
    beneficiary: payoutBeneficiary.PayoutBeneficiaryKind
    reason: redirectReason.RedirectReasonKind
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "PayoutRedirected":
        return cls(
        channel=obj["channel"],
        owner=obj["owner"],
        amount=obj["amount"],
        beneficiary=payoutBeneficiary.from_decoded(obj["beneficiary"]),
        reason=redirectReason.from_decoded(obj["reason"]),
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "channel": self.channel,
                "owner": self.owner,
                "amount": self.amount,
                "beneficiary": self.beneficiary.to_encodable(),
                "reason": self.reason.to_encodable(),
                }

    def to_json(self) -> PayoutRedirectedJSON:
        return {
                "channel": str(self.channel),
                "owner": str(self.owner),
                "amount": self.amount,
                "beneficiary": self.beneficiary.to_json(),
                "reason": self.reason.to_json(),
                }

    @classmethod
    def from_json(cls, obj: PayoutRedirectedJSON) -> "PayoutRedirected":
        return cls(
                channel=SolPubkey.from_string(obj["channel"]),
                owner=SolPubkey.from_string(obj["owner"]),
                amount=obj["amount"],
                beneficiary=payoutBeneficiary.from_json(obj["beneficiary"]),
                reason=redirectReason.from_json(obj["reason"]),
        )






