'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class UnsupportedExtensionJSON(typing.TypedDict):
    kind: typing.Literal["UnsupportedExtension"]


@dataclass
class UnsupportedExtension:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> UnsupportedExtensionJSON:
        return UnsupportedExtensionJSON(
            kind="UnsupportedExtension",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UnsupportedExtension": {},
        }




class ClosedOrMalformedJSON(typing.TypedDict):
    kind: typing.Literal["ClosedOrMalformed"]


@dataclass
class ClosedOrMalformed:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> ClosedOrMalformedJSON:
        return ClosedOrMalformedJSON(
            kind="ClosedOrMalformed",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "ClosedOrMalformed": {},
        }




class NotInitializedJSON(typing.TypedDict):
    kind: typing.Literal["NotInitialized"]


@dataclass
class NotInitialized:
    discriminator: typing.ClassVar = 2
    def to_json(self) -> NotInitializedJSON:
        return NotInitializedJSON(
            kind="NotInitialized",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "NotInitialized": {},
        }




class ReassignedAuthorityJSON(typing.TypedDict):
    kind: typing.Literal["ReassignedAuthority"]


@dataclass
class ReassignedAuthority:
    discriminator: typing.ClassVar = 3
    def to_json(self) -> ReassignedAuthorityJSON:
        return ReassignedAuthorityJSON(
            kind="ReassignedAuthority",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "ReassignedAuthority": {},
        }





RedirectReasonKind = typing.Union[
    UnsupportedExtension,
    ClosedOrMalformed,
    NotInitialized,
    ReassignedAuthority,
]
RedirectReasonJSON = typing.Union[
    UnsupportedExtensionJSON,
    ClosedOrMalformedJSON,
    NotInitializedJSON,
    ReassignedAuthorityJSON,
]

def from_decoded(obj: dict) -> RedirectReasonKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "UnsupportedExtension" in obj:
      return UnsupportedExtension()
    if "ClosedOrMalformed" in obj:
      return ClosedOrMalformed()
    if "NotInitialized" in obj:
      return NotInitialized()
    if "ReassignedAuthority" in obj:
      return ReassignedAuthority()
    raise ValueError("Invalid enum object")

def from_json(obj: RedirectReasonJSON) -> RedirectReasonKind:
    if obj["kind"] == "UnsupportedExtension":
        return UnsupportedExtension()

    if obj["kind"] == "ClosedOrMalformed":
        return ClosedOrMalformed()

    if obj["kind"] == "NotInitialized":
        return NotInitialized()

    if obj["kind"] == "ReassignedAuthority":
        return ReassignedAuthority()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"UnsupportedExtension" / borsh.CStruct(),
"ClosedOrMalformed" / borsh.CStruct(),
"NotInitialized" / borsh.CStruct(),
"ReassignedAuthority" / borsh.CStruct(),
)
