'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class SettlementWatermarksJSON(typing.TypedDict):
    settled: int
    payoutWatermark: int

@dataclass
class SettlementWatermarks:
    layout: typing.ClassVar = borsh.CStruct(
        "settled" /borsh.U64,
        "payoutWatermark" /borsh.U64,
        )
    #fields
    settled: int
    payoutWatermark: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "SettlementWatermarks":
        return cls(
        settled=obj["settled"],
        payoutWatermark=obj["payoutWatermark"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "settled": self.settled,
                "payoutWatermark": self.payoutWatermark,
                }

    def to_json(self) -> SettlementWatermarksJSON:
        return {
                "settled": self.settled,
                "payoutWatermark": self.payoutWatermark,
                }

    @classmethod
    def from_json(cls, obj: SettlementWatermarksJSON) -> "SettlementWatermarks":
        return cls(
                settled=obj["settled"],
                payoutWatermark=obj["payoutWatermark"],
        )






