'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class VoucherArgsJSON(typing.TypedDict):
    channelId: str
    cumulativeAmount: int
    expiresAt: int

@dataclass
class VoucherArgs:
    layout: typing.ClassVar = borsh.CStruct(
        "channelId" /BorshPubkey,
        "cumulativeAmount" /borsh.U64,
        "expiresAt" /borsh.I64,
        )
    #fields
    channelId: SolPubkey
    cumulativeAmount: int
    expiresAt: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "VoucherArgs":
        return cls(
        channelId=obj["channelId"],
        cumulativeAmount=obj["cumulativeAmount"],
        expiresAt=obj["expiresAt"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "channelId": self.channelId,
                "cumulativeAmount": self.cumulativeAmount,
                "expiresAt": self.expiresAt,
                }

    def to_json(self) -> VoucherArgsJSON:
        return {
                "channelId": str(self.channelId),
                "cumulativeAmount": self.cumulativeAmount,
                "expiresAt": self.expiresAt,
                }

    @classmethod
    def from_json(cls, obj: VoucherArgsJSON) -> "VoucherArgs":
        return cls(
                channelId=SolPubkey.from_string(obj["channelId"]),
                cumulativeAmount=obj["cumulativeAmount"],
                expiresAt=obj["expiresAt"],
        )






