'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing

from solders.pubkey import Pubkey as SolPubkey

from ..program_id import PAYMENT_CHANNELS_PROGRAM_ADDRESS

def find_event_authority_pda() -> typing.Tuple[SolPubkey, int]:
    seeds = [
        b"event_authority",
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            PAYMENT_CHANNELS_PROGRAM_ADDRESS
            )

    return address, bump


