'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing

from solders.pubkey import Pubkey as SolPubkey

from ..program_id import SUBSCRIPTIONS_PROGRAM_ADDRESS

def find_event_authority_pda() -> typing.Tuple[SolPubkey, int]:
    seeds = [
        b"event_authority",
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump


def find_fixed_delegation_pda(subscriptionAuthority: SolPubkey, delegator: SolPubkey, delegatee: SolPubkey, nonce: int) -> typing.Tuple[SolPubkey, int]:
    seeds = [
        b"delegation",
        bytes(subscriptionAuthority),
        bytes(delegator),
        bytes(delegatee),
        nonce.to_bytes(8, byteorder='little'),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump


def find_plan_pda(owner: SolPubkey, planId: int) -> typing.Tuple[SolPubkey, int]:
    seeds = [
        b"plan",
        bytes(owner),
        planId.to_bytes(8, byteorder='little'),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump


def find_recurring_delegation_pda(subscriptionAuthority: SolPubkey, delegator: SolPubkey, delegatee: SolPubkey, nonce: int) -> typing.Tuple[SolPubkey, int]:
    seeds = [
        b"delegation",
        bytes(subscriptionAuthority),
        bytes(delegator),
        bytes(delegatee),
        nonce.to_bytes(8, byteorder='little'),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump


def find_subscription_authority_pda(user: SolPubkey, tokenMint: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
        b"SubscriptionAuthority",
        bytes(user),
        bytes(tokenMint),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump


def find_subscription_delegation_pda(planPda: SolPubkey, subscriber: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
        b"subscription",
        bytes(planPda),
        bytes(subscriber),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            SUBSCRIPTIONS_PROGRAM_ADDRESS
            )

    return address, bump


