import Foundation
import Testing
@testable import SolanaMpp

/// ATA derivation golden vectors generated by a Rust binary against
/// solana-pubkey 3.x `Pubkey::find_program_address`. Each fixture
/// captures the expected address plus the bump byte the spine
/// converges to.
@Suite("Associated Token Account derivation parity with Rust")
struct AtaTests {
    struct Vector {
        let label: String
        let owner: String
        let mint: String
        let tokenProgram: String
        let expectedAta: String
    }

    static let vectors: [Vector] = [
        Vector(
            label: "usdc_alice",
            owner: "5wEwLBR3aTGdz8wWUFKafdGiLcQNqotQK1ndJxXLfHir",
            mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
            tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            expectedAta: "62KBveQZcf9Xcw4EUNP3hfGFevkCUSdE3wRZueQfLoow"
        ),
        Vector(
            label: "usdc_system",
            owner: "11111111111111111111111111111111",
            mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
            tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            expectedAta: "HJt8Tjdsc9ms9i4WCZEzhzr4oyf3ANcdzXrNdLPFqm3M"
        ),
        Vector(
            label: "usdt_alice",
            owner: "5wEwLBR3aTGdz8wWUFKafdGiLcQNqotQK1ndJxXLfHir",
            mint: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
            tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            expectedAta: "8Dtq7ts41S8qnLfj6xDtwcZPgRQBKU1t5CPAVFS2Xxgf"
        ),
        Vector(
            label: "t22_alice",
            owner: "5wEwLBR3aTGdz8wWUFKafdGiLcQNqotQK1ndJxXLfHir",
            mint: "MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5",
            tokenProgram: "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
            expectedAta: "4JB2LQ6aZesQeUAbMYkKMRzMmAq2xJB8y97q3xqFYP3k"
        ),
    ]

    @Test
    func atasMatchRustGoldenVectors() throws {
        for vector in Self.vectors {
            let owner = try Pubkey(base58: vector.owner)
            let mint = try Pubkey(base58: vector.mint)
            let tokenProgram = try Pubkey(base58: vector.tokenProgram)
            let derived = try AssociatedTokenAccount.address(
                owner: owner,
                mint: mint,
                tokenProgram: tokenProgram
            )
            #expect(derived.base58 == vector.expectedAta, "mismatch for \(vector.label)")
        }
    }
}
