'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import PAYMENT_CHANNELS_PROGRAM_ADDRESS
class DistributeArgs(typing.TypedDict):
    distributeArgs:types.distributeArgs.DistributeArgs


layout = borsh.CStruct(
    "distributeArgs" /types.distributeArgs.DistributeArgs.layout,
    )


class DistributeAccounts(typing.TypedDict):
    channel:SolPubkey
    payer:SolPubkey
    rentPayer:SolPubkey
    channelTokenAccount:SolPubkey
    payerTokenAccount:SolPubkey
    payeeTokenAccount:SolPubkey
    treasuryTokenAccount:SolPubkey
    mint:SolPubkey
    tokenProgram:SolPubkey
    eventAuthority:SolPubkey
    selfProgram:SolPubkey

def Distribute(
    args: DistributeArgs,
    accounts: DistributeAccounts,
    program_id: SolPubkey =  PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["channel"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["payer"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["rentPayer"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["channelTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["payerTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["payeeTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["treasuryTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["eventAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["selfProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x07"


    encoded_args = layout.build({
        "distributeArgs":args["distributeArgs"].to_encodable(),
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)


def find_EventAuthority() -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"event_authority",
    ]

    address, bump = SolPubkey.find_program_address(seeds,
         PAYMENT_CHANNELS_PROGRAM_ADDRESS
            )

    return address, bump





