'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PAYMENT_CHANNELS_PROGRAM_ADDRESS

class SettleAccounts(typing.TypedDict):
    channel:SolPubkey
    instructionsSysvar:SolPubkey

def Settle(
    accounts: SettleAccounts,
    program_id: SolPubkey =  PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["channel"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["instructionsSysvar"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x02"


    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



