'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import PAYMENT_CHANNELS_PROGRAM_ADDRESS
class TopUpArgs(typing.TypedDict):
    topUpArgs:types.topUpArgs.TopUpArgs


layout = borsh.CStruct(
    "topUpArgs" /types.topUpArgs.TopUpArgs.layout,
    )


class TopUpAccounts(typing.TypedDict):
    payer:SolPubkey
    channel:SolPubkey
    payerTokenAccount:SolPubkey
    channelTokenAccount:SolPubkey
    mint:SolPubkey
    tokenProgram:SolPubkey

def TopUp(
    args: TopUpArgs,
    accounts: TopUpAccounts,
    program_id: SolPubkey =  PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["channel"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["payerTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["channelTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x03"


    encoded_args = layout.build({
        "topUpArgs":args["topUpArgs"].to_encodable(),
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



