'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PAYMENT_CHANNELS_PROGRAM_ADDRESS

class WithdrawPayerAccounts(typing.TypedDict):
    payer:SolPubkey
    channel:SolPubkey
    channelTokenAccount:SolPubkey
    payerTokenAccount:SolPubkey
    mint:SolPubkey
    tokenProgram:SolPubkey

def WithdrawPayer(
    accounts: WithdrawPayerAccounts,
    program_id: SolPubkey =  PAYMENT_CHANNELS_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["channel"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["channelTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["payerTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x08"


    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



