package com.solana.paykit.paycore

// MppException lives in the same package (paycore)

import java.io.ByteArrayOutputStream

/**
 * Solana transaction codec covering legacy and v0 (versioned) messages.
 *
 * Wire-format reference: the Solana SDK
 * (`solana-transaction` / `solana-message` crates) and the Rust spine at
 * `rust/src/client/charge.rs` which uses
 * `solana_message::Message::new_with_blockhash` followed by
 * `bincode::serialize` to produce the credential payload.
 *
 * The serialized output of `buildLegacyMessage` + `serializeLegacyTransaction`
 * is asserted byte-for-byte against a golden vector generated by Rust at
 * `rust/examples/golden_tx.rs`.
 */
object Transaction {
    /** Maximum value that fits in a Solana compact-u16. */
    private const val COMPACT_U16_MAX = 0xffff

    /**
     * Compact-u16 ("shortvec") length encoder used everywhere a Solana
     * message counts elements (signatures, accounts, instructions, etc.).
     *
     * Spec: 7 bits per byte little-endian, MSB set when more bytes follow.
     */
    fun encodeCompactU16(value: Int): ByteArray {
        require(value in 0..COMPACT_U16_MAX) { "compact-u16 out of range: $value" }
        val out = ByteArrayOutputStream(3)
        var remaining = value
        while (true) {
            val low = remaining and 0x7f
            remaining = remaining ushr 7
            if (remaining == 0) {
                out.write(low)
                return out.toByteArray()
            } else {
                out.write(low or 0x80)
            }
        }
    }

    // ── Account compaction ──

    /**
     * Compacts a list of instructions into the canonical Solana message
     * account-key order:
     *
     *   [writable signers, readonly signers, writable non-signers, readonly non-signers]
     *
     * The fee payer is always the first writable signer. The returned
     * triple is (orderedKeys, header, instructionAccountIndices).
     */
    internal data class Compaction(
        val keys: List<PublicKey>,
        val header: MessageHeader,
        val instructionAccountIndices: List<ByteArray>,
        val instructionProgramIndices: ByteArray,
    )

    /** 3 byte message header (Solana wire format). */
    data class MessageHeader(
        val numRequiredSignatures: Int,
        val numReadonlySigned: Int,
        val numReadonlyUnsigned: Int,
    )

    internal fun compactAccounts(
        feePayer: PublicKey,
        instructions: List<Instruction>,
    ): Compaction {
        // Walk every instruction's accounts plus the program id; track per-key
        // signer + writable flags. The fee payer is always present, signer,
        // writable.
        data class Slot(var isSigner: Boolean, var isWritable: Boolean)
        val seen = LinkedHashMap<String, Slot>()
        seen[feePayer.toBase58()] = Slot(isSigner = true, isWritable = true)
        for (ix in instructions) {
            for (account in ix.accounts) {
                val slot = seen.getOrPut(account.pubkey) { Slot(false, false) }
                if (account.isSigner) slot.isSigner = true
                if (account.isWritable) slot.isWritable = true
            }
            // Program ids are read-only, non-signer accounts.
            seen.getOrPut(ix.programId) { Slot(false, false) }
        }

        // Partition into the four canonical buckets while preserving first-seen
        // order inside each bucket so the layout is deterministic.
        val writableSigners = mutableListOf<String>()
        val readonlySigners = mutableListOf<String>()
        val writableNonSigners = mutableListOf<String>()
        val readonlyNonSigners = mutableListOf<String>()
        for ((pubkey, slot) in seen) {
            when {
                slot.isSigner && slot.isWritable -> writableSigners.add(pubkey)
                slot.isSigner && !slot.isWritable -> readonlySigners.add(pubkey)
                !slot.isSigner && slot.isWritable -> writableNonSigners.add(pubkey)
                else -> readonlyNonSigners.add(pubkey)
            }
        }

        // Fee payer must lead the writable-signer bucket. The first writable
        // signer is the fee payer by Solana's message rules, and the loop
        // above seeds the LinkedHashMap with it first, so this is already
        // true; assert defensively.
        check(writableSigners.firstOrNull() == feePayer.toBase58()) {
            "fee payer must be the first writable signer"
        }

        val orderedPubkeys = writableSigners + readonlySigners + writableNonSigners + readonlyNonSigners
        val orderedKeys = orderedPubkeys.map { PublicKey.fromBase58(it) }
        val indexOf = orderedPubkeys.withIndex().associate { (i, key) -> key to i }
        val header = MessageHeader(
            numRequiredSignatures = writableSigners.size + readonlySigners.size,
            numReadonlySigned = readonlySigners.size,
            numReadonlyUnsigned = readonlyNonSigners.size,
        )

        val ixAccountIndices = ArrayList<ByteArray>(instructions.size)
        val ixProgramIndices = ByteArray(instructions.size)
        for ((index, ix) in instructions.withIndex()) {
            val accountIndices = ByteArray(ix.accounts.size)
            for ((position, meta) in ix.accounts.withIndex()) {
                val keyIndex = indexOf[meta.pubkey]
                    ?: throw MppException.InvalidTransaction("account ${meta.pubkey} not in keys")
                if (keyIndex > 255) {
                    throw MppException.InvalidTransaction("account index $keyIndex exceeds u8")
                }
                accountIndices[position] = keyIndex.toByte()
            }
            val programIndex = indexOf[ix.programId]
                ?: throw MppException.InvalidTransaction("program ${ix.programId} not in keys")
            if (programIndex > 255) {
                throw MppException.InvalidTransaction("program index $programIndex exceeds u8")
            }
            ixAccountIndices.add(accountIndices)
            ixProgramIndices[index] = programIndex.toByte()
        }

        return Compaction(orderedKeys, header, ixAccountIndices, ixProgramIndices)
    }

    // ── Legacy message serialization ──

    /**
     * Serializes a legacy Solana message to wire bytes. The output matches
     * `solana_message::Message::serialize` byte-for-byte.
     */
    fun buildLegacyMessage(
        feePayer: PublicKey,
        recentBlockhash: ByteArray,
        instructions: List<Instruction>,
    ): LegacyMessage {
        require(recentBlockhash.size == 32) {
            "recentBlockhash must be 32 bytes (got ${recentBlockhash.size})"
        }
        val compaction = compactAccounts(feePayer, instructions)
        return LegacyMessage(
            header = compaction.header,
            accountKeys = compaction.keys,
            recentBlockhash = recentBlockhash.copyOf(),
            instructions = instructions.mapIndexed { i, ix ->
                CompiledInstruction(
                    programIndex = compaction.instructionProgramIndices[i],
                    accountIndices = compaction.instructionAccountIndices[i],
                    data = ix.data.copyOf(),
                )
            },
        )
    }

    /** Compact-u16 length prefix + account index bytes + data length + data bytes. */
    data class CompiledInstruction(
        val programIndex: Byte,
        val accountIndices: ByteArray,
        val data: ByteArray,
    ) {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is CompiledInstruction) return false
            return programIndex == other.programIndex &&
                accountIndices.contentEquals(other.accountIndices) &&
                data.contentEquals(other.data)
        }

        override fun hashCode(): Int {
            var result = programIndex.toInt()
            result = 31 * result + accountIndices.contentHashCode()
            result = 31 * result + data.contentHashCode()
            return result
        }
    }

    /** Serialized legacy Solana message. */
    data class LegacyMessage(
        val header: MessageHeader,
        val accountKeys: List<PublicKey>,
        val recentBlockhash: ByteArray,
        val instructions: List<CompiledInstruction>,
    ) {
        /** Wire-format bytes. */
        fun serialize(): ByteArray {
            val out = ByteArrayOutputStream()
            out.write(header.numRequiredSignatures)
            out.write(header.numReadonlySigned)
            out.write(header.numReadonlyUnsigned)
            out.write(encodeCompactU16(accountKeys.size))
            for (key in accountKeys) {
                out.write(key.bytes)
            }
            out.write(recentBlockhash)
            out.write(encodeCompactU16(instructions.size))
            for (ix in instructions) {
                out.write(ix.programIndex.toInt() and 0xff)
                out.write(encodeCompactU16(ix.accountIndices.size))
                out.write(ix.accountIndices)
                out.write(encodeCompactU16(ix.data.size))
                out.write(ix.data)
            }
            return out.toByteArray()
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is LegacyMessage) return false
            return header == other.header &&
                accountKeys == other.accountKeys &&
                recentBlockhash.contentEquals(other.recentBlockhash) &&
                instructions == other.instructions
        }

        override fun hashCode(): Int {
            var result = header.hashCode()
            result = 31 * result + accountKeys.hashCode()
            result = 31 * result + recentBlockhash.contentHashCode()
            result = 31 * result + instructions.hashCode()
            return result
        }
    }

    /**
     * Serializes a legacy Transaction (the bincode shape Rust uses on the
     * wire). Layout:
     *
     *   compact-u16 N
     *   N × 64-byte signature
     *   message bytes
     *
     * Slots without a signature are written as 64 zero bytes (Solana
     * placeholder convention).
     */
    fun serializeLegacyTransaction(message: LegacyMessage, signatures: List<ByteArray?>): ByteArray {
        require(signatures.size == message.header.numRequiredSignatures) {
            "expected ${message.header.numRequiredSignatures} signature slots, got ${signatures.size}"
        }
        signatures.forEach { sig ->
            if (sig != null) {
                require(sig.size == 64) { "signatures must be 64 bytes" }
            }
        }
        val out = ByteArrayOutputStream()
        out.write(encodeCompactU16(signatures.size))
        for (sig in signatures) {
            out.write(sig ?: ByteArray(64))
        }
        out.write(message.serialize())
        return out.toByteArray()
    }

    // ── v0 (versioned) message ──

    /**
     * Serializes a v0 (versioned) message. Wire format equals the legacy
     * layout with a single-byte version prefix `0x80` (1 << 7 | 0) and a
     * compact-u16-counted address-table-lookups tail.
     *
     * This client never emits address-table lookups (the MPP charge
     * intent does not use them); the tail is therefore always a single
     * zero byte.
     */
    fun buildV0Message(
        feePayer: PublicKey,
        recentBlockhash: ByteArray,
        instructions: List<Instruction>,
    ): V0Message {
        require(recentBlockhash.size == 32) {
            "recentBlockhash must be 32 bytes (got ${recentBlockhash.size})"
        }
        val compaction = compactAccounts(feePayer, instructions)
        return V0Message(
            header = compaction.header,
            accountKeys = compaction.keys,
            recentBlockhash = recentBlockhash.copyOf(),
            instructions = instructions.mapIndexed { i, ix ->
                CompiledInstruction(
                    programIndex = compaction.instructionProgramIndices[i],
                    accountIndices = compaction.instructionAccountIndices[i],
                    data = ix.data.copyOf(),
                )
            },
        )
    }

    /** Serialized v0 Solana message. */
    data class V0Message(
        val header: MessageHeader,
        val accountKeys: List<PublicKey>,
        val recentBlockhash: ByteArray,
        val instructions: List<CompiledInstruction>,
    ) {
        fun serialize(): ByteArray {
            val out = ByteArrayOutputStream()
            // Version prefix: high bit set + version 0.
            out.write(0x80)
            out.write(header.numRequiredSignatures)
            out.write(header.numReadonlySigned)
            out.write(header.numReadonlyUnsigned)
            out.write(encodeCompactU16(accountKeys.size))
            for (key in accountKeys) {
                out.write(key.bytes)
            }
            out.write(recentBlockhash)
            out.write(encodeCompactU16(instructions.size))
            for (ix in instructions) {
                out.write(ix.programIndex.toInt() and 0xff)
                out.write(encodeCompactU16(ix.accountIndices.size))
                out.write(ix.accountIndices)
                out.write(encodeCompactU16(ix.data.size))
                out.write(ix.data)
            }
            // Address table lookups (none).
            out.write(encodeCompactU16(0))
            return out.toByteArray()
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is V0Message) return false
            return header == other.header &&
                accountKeys == other.accountKeys &&
                recentBlockhash.contentEquals(other.recentBlockhash) &&
                instructions == other.instructions
        }

        override fun hashCode(): Int {
            var result = header.hashCode()
            result = 31 * result + accountKeys.hashCode()
            result = 31 * result + recentBlockhash.contentHashCode()
            result = 31 * result + instructions.hashCode()
            return result
        }
    }

    /**
     * Serializes a v0 VersionedTransaction (bincode shape). Identical
     * outer layout to the legacy transaction: compact-u16 signature
     * count, N × 64 byte signatures, message bytes (with the v0 prefix).
     */
    fun serializeV0Transaction(message: V0Message, signatures: List<ByteArray?>): ByteArray {
        require(signatures.size == message.header.numRequiredSignatures) {
            "expected ${message.header.numRequiredSignatures} signature slots, got ${signatures.size}"
        }
        signatures.forEach { sig ->
            if (sig != null) require(sig.size == 64) { "signatures must be 64 bytes" }
        }
        val out = ByteArrayOutputStream()
        out.write(encodeCompactU16(signatures.size))
        for (sig in signatures) {
            out.write(sig ?: ByteArray(64))
        }
        out.write(message.serialize())
        return out.toByteArray()
    }
}
